export interface SeedGrammarQuestion {
  prompt: string;
  options: string[];
  correctIndex: number;
  explanationVi: string;
}

export const EXTRA_GRAMMAR_QUESTIONS: Record<string, SeedGrammarQuestion[]> = {
  nouns: [
    {
      prompt: "The company's ----- in the local market has been steady over the past decade.",
      options: ["grow", "growth", "growing", "grew"],
      correctIndex: 1,
      explanationVi: "Sau tính từ sở hữu 'company's' cần một danh từ: 'growth' (sự tăng trưởng).",
    },
    {
      prompt: "Please bring your ID card and proof of ----- to the registration desk.",
      options: ["identify", "identification", "identified", "identifying"],
      correctIndex: 1,
      explanationVi: "Sau giới từ 'of' cần danh từ: 'identification' (giấy tờ tùy thân).",
    },
    {
      prompt: "The department requested additional ----- to complete the audit on schedule.",
      options: ["assist", "assistance", "assisted", "assisting"],
      correctIndex: 1,
      explanationVi: "Sau tính từ 'additional' cần danh từ không đếm được: 'assistance' (sự hỗ trợ).",
    },
    {
      prompt: "Employees should direct all ----- regarding payroll to the HR office.",
      options: ["inquire", "inquiry", "inquiries", "inquiring"],
      correctIndex: 2,
      explanationVi: "'All' đi với danh từ đếm được ở dạng số nhiều: 'inquiries' (các thắc mắc).",
    },
    {
      prompt: "The manufacturing plant purchased new ----- to increase production capacity.",
      options: ["equip", "equipment", "equipments", "equipped"],
      correctIndex: 1,
      explanationVi: "'Equipment' là danh từ không đếm được nên không có dạng số nhiều 'equipments'; đây là danh từ đúng sau tính từ 'new'.",
    },
    {
      prompt: "The board discussed several ----- for improving customer retention.",
      options: ["suggest", "suggestion", "suggestions", "suggesting"],
      correctIndex: 2,
      explanationVi: "'Several' đi với danh từ đếm được số nhiều: 'suggestions' (các đề xuất).",
    },
    {
      prompt: "The warehouse manager submitted a detailed ----- of the damaged goods.",
      options: ["describe", "description", "described", "describing"],
      correctIndex: 1,
      explanationVi: "Sau tính từ 'detailed' cần danh từ: 'description' (bản mô tả).",
    },
    {
      prompt: "Due to budget -----, several projects have been postponed.",
      options: ["constrain", "constraint", "constraints", "constraining"],
      correctIndex: 2,
      explanationVi: "'Budget constraints' (hạn chế ngân sách) là cụm danh từ số nhiều quen thuộc sau 'due to'.",
    },
    {
      prompt: "The firm's ----- with international regulations was praised by auditors.",
      options: ["comply", "compliance", "complied", "compliant"],
      correctIndex: 1,
      explanationVi: "Sau tính từ sở hữu 'firm's' cần danh từ: 'compliance' (sự tuân thủ).",
    },
    {
      prompt: "All visitors need prior ----- before accessing the server room.",
      options: ["authorize", "authorization", "authorized", "authorizing"],
      correctIndex: 1,
      explanationVi: "Sau tính từ 'prior' cần danh từ: 'authorization' (sự cho phép).",
    },
    {
      prompt: "The ----- between the two departments improved after the workshop.",
      options: ["communicate", "communication", "communicated", "communicating"],
      correctIndex: 1,
      explanationVi: "Sau mạo từ 'the' và trước 'between' cần danh từ: 'communication' (sự giao tiếp).",
    },
    {
      prompt: "The company offers a wide ----- of office supplies at discounted rates.",
      options: ["vary", "variety", "varied", "varying"],
      correctIndex: 1,
      explanationVi: "Sau tính từ 'wide' cần danh từ: 'variety' (sự đa dạng), trong cụm 'a wide variety of'.",
    },
  ],
  pronouns: [
    {
      prompt: "The manager asked the assistant to send the documents to -----.",
      options: ["he", "him", "his", "himself"],
      correctIndex: 1,
      explanationVi: "Sau giới từ 'to' cần đại từ tân ngữ: 'him'.",
    },
    {
      prompt: "The empty desk near the window belongs to the interns; it is -----.",
      options: ["they", "them", "their", "theirs"],
      correctIndex: 3,
      explanationVi: "Đại từ sở hữu đứng một mình, không kèm danh từ theo sau, dùng 'theirs'.",
    },
    {
      prompt: "The CEO ----- announced the merger during the press conference.",
      options: ["he", "him", "his", "himself"],
      correctIndex: 3,
      explanationVi: "Đại từ phản thân dùng để nhấn mạnh chủ ngữ tự thực hiện hành động: 'himself'.",
    },
    {
      prompt: "Our team finished the project faster than ----- did.",
      options: ["them", "their", "they", "theirs"],
      correctIndex: 2,
      explanationVi: "Trước động từ 'did' cần đại từ chủ ngữ: 'they'.",
    },
    {
      prompt: "The corporation increased ----- investment in renewable energy last year.",
      options: ["it", "its", "itself", "it's"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'investment' cần tính từ sở hữu 'its', không nhầm với 'it's' (dạng rút gọn của 'it is').",
    },
    {
      prompt: "Please let ----- know if you have any questions about the itinerary.",
      options: ["we", "us", "our", "ours"],
      correctIndex: 1,
      explanationVi: "Sau động từ 'let' cần đại từ tân ngữ: 'us'.",
    },
    {
      prompt: "The clients preferred to negotiate the contract ----- rather than through email.",
      options: ["them", "themselves", "their", "theirs"],
      correctIndex: 1,
      explanationVi: "Đại từ phản thân nhấn mạnh chủ ngữ tự thực hiện hành động: 'themselves' (tự họ thương lượng).",
    },
    {
      prompt: "Each applicant must submit ----- résumé along with a cover letter.",
      options: ["he", "his or her", "him", "himself"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'résumé' cần tính từ sở hữu; 'his or her' phù hợp với chủ ngữ trung tính 'each applicant'.",
    },
    {
      prompt: "The two companies reached an agreement that benefits ----- equally.",
      options: ["they", "them", "their", "themselves"],
      correctIndex: 1,
      explanationVi: "Sau động từ 'benefits' cần đại từ tân ngữ: 'them'.",
    },
    {
      prompt: "If you need further assistance, please contact ----- directly.",
      options: ["I", "me", "my", "mine"],
      correctIndex: 1,
      explanationVi: "Sau động từ 'contact' cần đại từ tân ngữ: 'me'.",
    },
    {
      prompt: "The company revised ----- return policy after receiving customer complaints.",
      options: ["it", "its", "itself", "it's"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'return policy' cần tính từ sở hữu 'its'.",
    },
    {
      prompt: "The committee received two proposals, but only ----- was approved.",
      options: ["one", "ones", "it", "that"],
      correctIndex: 0,
      explanationVi: "Đại từ bất định 'one' thay thế cho 'one of the two proposals'.",
    },
    {
      prompt: "The training materials are for new hires; ----- who need a refresher may also request a copy.",
      options: ["those", "that", "it", "they"],
      correctIndex: 0,
      explanationVi: "Cấu trúc 'those who...' (những người mà...) rất phổ biến trong TOEIC.",
    },
  ],
  adjectives: [
    {
      prompt: "The clinic offers ----- healthcare services to all local residents.",
      options: ["afford", "affordable", "affordably", "affordability"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'healthcare services' cần tính từ: 'affordable' (có giá cả phải chăng).",
    },
    {
      prompt: "The new marketing strategy seems ----- compared to last year's approach.",
      options: ["effect", "effective", "effectively", "effectiveness"],
      correctIndex: 1,
      explanationVi: "Sau động từ liên kết 'seems' cần một tính từ: 'effective'.",
    },
    {
      prompt: "The quarterly sales results were quite ----- for the entire team.",
      options: ["surprise", "surprised", "surprising", "surprisingly"],
      correctIndex: 2,
      explanationVi: "'Results' là chủ thể gây ra cảm giác ngạc nhiên nên dùng tính từ -ing mang nghĩa chủ động: 'surprising'.",
    },
    {
      prompt: "Many customers were ----- with the delay in shipment.",
      options: ["disappoint", "disappointing", "disappointed", "disappointment"],
      correctIndex: 2,
      explanationVi: "'Customers' là người cảm thấy nên dùng tính từ -ed mang nghĩa bị động: 'disappointed'.",
    },
    {
      prompt: "The proposal appears ----- enough to gain approval from the board.",
      options: ["convince", "convinced", "convincing", "conviction"],
      correctIndex: 2,
      explanationVi: "'Proposal' chủ động tạo ra sự thuyết phục nên dùng tính từ -ing: 'convincing'.",
    },
    {
      prompt: "The proposal received ----- approval from all board members.",
      options: ["unanimous", "unanimously", "unanimity", "unanimousness"],
      correctIndex: 0,
      explanationVi: "Trước danh từ 'approval' cần tính từ: 'unanimous' (nhất trí).",
    },
    {
      prompt: "The company's new headquarters is very -----, just minutes from the airport.",
      options: ["convenient", "conveniently", "convenience", "convenience's"],
      correctIndex: 0,
      explanationVi: "Sau động từ liên kết 'is' cần tính từ: 'convenient'.",
    },
    {
      prompt: "Staff members found the new software surprisingly ----- to use.",
      options: ["ease", "easy", "easily", "easiness"],
      correctIndex: 1,
      explanationVi: "Cấu trúc 'found + tân ngữ + tính từ': 'found the software easy to use'.",
    },
    {
      prompt: "The results of the survey were quite ----- to senior management.",
      options: ["reveal", "revealing", "revealed", "revelation"],
      correctIndex: 1,
      explanationVi: "'Results' chủ động tiết lộ thông tin nên dùng tính từ -ing: 'revealing'.",
    },
    {
      prompt: "It is ----- for all employees to complete the safety training by Friday.",
      options: ["mandate", "mandatory", "mandated", "mandating"],
      correctIndex: 1,
      explanationVi: "Cấu trúc 'It is + tính từ + for someone + to V': 'mandatory' (bắt buộc).",
    },
    {
      prompt: "The negotiation process turned out to be more ----- than expected.",
      options: ["complicate", "complicated", "complication", "complicating"],
      correctIndex: 1,
      explanationVi: "Sau động từ liên kết 'turned out to be' cần tính từ: 'complicated'.",
    },
    {
      prompt: "Only ----- candidates will be contacted for a second interview.",
      options: ["qualify", "qualified", "qualifying", "qualification"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'candidates' cần tính từ -ed mang nghĩa bị động: 'qualified' (đủ tiêu chuẩn).",
    },
  ],
  adverbs: [
    {
      prompt: "The assistant ----- organized the files before the inspection.",
      options: ["careful", "carefully", "care", "careless"],
      correctIndex: 1,
      explanationVi: "Cần trạng từ bổ nghĩa cho động từ 'organized': 'carefully'.",
    },
    {
      prompt: "The director ----- attends the weekly planning meetings.",
      options: ["usual", "usually", "usualness", "use"],
      correctIndex: 1,
      explanationVi: "Trạng từ tần suất 'usually' đứng trước động từ thường 'attends'.",
    },
    {
      prompt: "The revised contract terms are ----- different from the original draft.",
      options: ["significant", "significance", "significantly", "signify"],
      correctIndex: 2,
      explanationVi: "Cần trạng từ bổ nghĩa cho tính từ 'different': 'significantly'.",
    },
    {
      prompt: "The new safety procedures have been ----- implemented across all branches.",
      options: ["success", "successful", "successfully", "succeed"],
      correctIndex: 2,
      explanationVi: "Trạng từ 'successfully' đứng giữa trợ động từ 'have been' và động từ chính 'implemented'.",
    },
    {
      prompt: "-----, the company decided to postpone the product launch until further notice.",
      options: ["Consequent", "Consequence", "Consequently", "Consequential"],
      correctIndex: 2,
      explanationVi: "Trạng từ liên kết 'Consequently' (do đó) đứng đầu câu, theo sau là dấu phẩy, để nối ý kết quả với câu trước.",
    },
    {
      prompt: "The new employee adapted ----- to the company culture.",
      options: ["quick", "quickly", "quicker", "quickness"],
      correctIndex: 1,
      explanationVi: "Cần trạng từ bổ nghĩa cho động từ 'adapted': 'quickly'.",
    },
    {
      prompt: "Management ----- reviews employee performance at the end of each quarter.",
      options: ["regular", "regularly", "regularity", "regulate"],
      correctIndex: 1,
      explanationVi: "Trạng từ tần suất 'regularly' đứng trước động từ thường 'reviews'.",
    },
    {
      prompt: "The proposal was ----- rejected due to budget constraints.",
      options: ["immediate", "immediately", "immediacy", "immediateness"],
      correctIndex: 1,
      explanationVi: "Cần trạng từ bổ nghĩa cho động từ bị động 'was rejected': 'immediately'.",
    },
    {
      prompt: "The two reports were ----- similar in their conclusions.",
      options: ["remark", "remarkable", "remarkably", "remarking"],
      correctIndex: 2,
      explanationVi: "Cần trạng từ bổ nghĩa cho tính từ 'similar': 'remarkably'.",
    },
    {
      prompt: "-----, the merger was completed ahead of schedule.",
      options: ["Surprise", "Surprised", "Surprisingly", "Surprising"],
      correctIndex: 2,
      explanationVi: "Trạng từ đứng đầu câu, theo sau là dấu phẩy: 'Surprisingly' (đáng ngạc nhiên là).",
    },
    {
      prompt: "The technician handled the malfunction ----- despite the pressure.",
      options: ["calm", "calmly", "calmness", "calming"],
      correctIndex: 1,
      explanationVi: "Cần trạng từ bổ nghĩa cho động từ 'handled': 'calmly'.",
    },
    {
      prompt: "Applications submitted ----- will not be considered.",
      options: ["late", "lately", "later", "latest"],
      correctIndex: 0,
      explanationVi: "'Late' làm trạng từ nghĩa 'trễ' (submitted late); 'lately' nghĩa là 'gần đây', sai nghĩa ở đây.",
    },
    {
      prompt: "The board members ----- agreed to postpone the vote until next month.",
      options: ["mutual", "mutually", "mutuality", "mutualize"],
      correctIndex: 1,
      explanationVi: "Cần trạng từ bổ nghĩa cho động từ 'agreed': 'mutually' (cùng nhau, đồng thuận).",
    },
  ],
  prepositions: [
    {
      prompt: "The training workshop will take place ----- March 15th.",
      options: ["in", "on", "at", "by"],
      correctIndex: 1,
      explanationVi: "Giới từ 'on' dùng cho ngày cụ thể.",
    },
    {
      prompt: "All new hires are responsible ----- completing the orientation program within their first week.",
      options: ["for", "of", "to", "with"],
      correctIndex: 0,
      explanationVi: "Collocation cố định: 'responsible for' (chịu trách nhiệm về).",
    },
    {
      prompt: "The company has operated in this region ----- more than two decades.",
      options: ["since", "for", "during", "within"],
      correctIndex: 1,
      explanationVi: "'For' đi với khoảng thời gian ('more than two decades'), khác với 'since' đi với mốc thời gian.",
    },
    {
      prompt: "The budget report will be finalized ----- accordance with the new financial guidelines.",
      options: ["in", "on", "at", "by"],
      correctIndex: 0,
      explanationVi: "Collocation cố định: 'in accordance with' (phù hợp với).",
    },
    {
      prompt: "The new intern will assist the marketing team ----- the end of the internship period.",
      options: ["by", "until", "since", "from"],
      correctIndex: 1,
      explanationVi: "'Until' diễn tả một hành động kéo dài liên tục đến một thời điểm, khác với 'by' chỉ hạn chót.",
    },
    {
      prompt: "The warehouse is located ----- the intersection of Fifth Avenue and Main Street.",
      options: ["in", "on", "at", "by"],
      correctIndex: 2,
      explanationVi: "Collocation cố định: 'at the intersection of' (tại giao lộ của).",
    },
    {
      prompt: "The manager has been working ----- this project since January.",
      options: ["on", "in", "at", "for"],
      correctIndex: 0,
      explanationVi: "Collocation cố định: 'work on a project' (làm việc cho một dự án).",
    },
    {
      prompt: "The invoice must be paid ----- 30 days of receipt.",
      options: ["within", "during", "for", "since"],
      correctIndex: 0,
      explanationVi: "'Within + khoảng thời gian' diễn tả 'trong vòng': 'within 30 days'.",
    },
    {
      prompt: "The committee will vote ----- the proposal at tomorrow's meeting.",
      options: ["on", "in", "at", "for"],
      correctIndex: 0,
      explanationVi: "Collocation cố định: 'vote on' (biểu quyết về).",
    },
    {
      prompt: "The company plans to expand ----- Southeast Asia next year.",
      options: ["to", "into", "on", "at"],
      correctIndex: 1,
      explanationVi: "Collocation cố định: 'expand into a region/market' (mở rộng sang).",
    },
    {
      prompt: "All employees, ----- their department, must complete the annual review.",
      options: ["regarding", "regardless of", "according to", "in spite"],
      correctIndex: 1,
      explanationVi: "'Regardless of' (bất kể) là cụm giới từ cố định.",
    },
    {
      prompt: "The proposal was approved ----- the condition that costs remain under budget.",
      options: ["on", "in", "at", "with"],
      correctIndex: 0,
      explanationVi: "Collocation cố định: 'on the condition that' (với điều kiện là).",
    },
    {
      prompt: "The new branch is expected to open ----- the third quarter of next year.",
      options: ["in", "on", "at", "by"],
      correctIndex: 0,
      explanationVi: "'In' dùng cho khoảng thời gian dài hơn như quý/tháng/năm: 'in the third quarter'.",
    },
  ],
  conjunctions: [
    {
      prompt: "The new manager is ----- skilled but also very approachable.",
      options: ["not only", "so", "either", "neither"],
      correctIndex: 0,
      explanationVi: "Cặp liên từ tương quan 'not only...but also'.",
    },
    {
      prompt: "The flight was delayed, ----- passengers were provided with meal vouchers.",
      options: ["so", "but", "or", "although"],
      correctIndex: 0,
      explanationVi: "'So' nối hai mệnh đề thể hiện quan hệ nguyên nhân - kết quả.",
    },
    {
      prompt: "The launch event was rescheduled ----- the venue was unavailable that week.",
      options: ["because", "because of", "due to", "despite"],
      correctIndex: 0,
      explanationVi: "Sau chỗ trống là mệnh đề đầy đủ chủ-vị ('the venue was unavailable'), cần liên từ 'because'.",
    },
    {
      prompt: "----- the tight deadline, the design team delivered the prototype on time.",
      options: ["Even though", "Although", "In spite of", "Because"],
      correctIndex: 2,
      explanationVi: "Sau chỗ trống là cụm danh từ ('the tight deadline'), cần giới từ 'in spite of', không dùng liên từ.",
    },
    {
      prompt: "The shipment will not be released ----- the payment is confirmed by the bank.",
      options: ["if", "unless", "although", "since"],
      correctIndex: 1,
      explanationVi: "'Unless' (= if...not) diễn tả điều kiện phủ định: lô hàng sẽ không được thả trừ khi thanh toán được xác nhận.",
    },
    {
      prompt: "The event will proceed as planned ----- it rains.",
      options: ["unless", "if", "because", "so"],
      correctIndex: 0,
      explanationVi: "'Unless' (trừ khi) phù hợp nghĩa: sự kiện vẫn diễn ra trừ khi trời mưa.",
    },
    {
      prompt: "----- the report was submitted late, the client accepted it without complaint.",
      options: ["Because", "Even though", "So", "Due to"],
      correctIndex: 1,
      explanationVi: "Sau chỗ trống là mệnh đề đầy đủ, cần liên từ nhượng bộ 'Even though' (mặc dù).",
    },
    {
      prompt: "The firm hired more staff ----- it could meet the rising demand.",
      options: ["so that", "so as", "in order", "because"],
      correctIndex: 0,
      explanationVi: "'So that + mệnh đề (S+V)' diễn tả mục đích; 'so as'/'in order' cần theo sau 'to + V', không phù hợp ở đây.",
    },
    {
      prompt: "Neither the marketing team ----- the sales team was informed of the change in advance.",
      options: ["nor", "or", "and", "but"],
      correctIndex: 0,
      explanationVi: "Cặp liên từ tương quan 'neither...nor'.",
    },
    {
      prompt: "The project can proceed ----- the client approves the final budget.",
      options: ["provided that", "despite", "although", "because of"],
      correctIndex: 0,
      explanationVi: "'Provided that' (miễn là) + mệnh đề diễn tả điều kiện; 'despite'/'because of' cần cụm danh từ, không phù hợp.",
    },
    {
      prompt: "The staff worked overtime, ----- they managed to finish the audit before the deadline.",
      options: ["and", "but", "or", "nor"],
      correctIndex: 0,
      explanationVi: "Liên từ kết hợp 'and' nối hai mệnh đề cùng chiều ý nghĩa.",
    },
    {
      prompt: "The manager will sign the contract ----- both parties agree on the final terms.",
      options: ["once", "despite", "although", "because of"],
      correctIndex: 0,
      explanationVi: "'Once' (ngay khi/một khi) giới thiệu mệnh đề điều kiện thời gian.",
    },
    {
      prompt: "The budget was cut significantly; -----, the project timeline had to be extended.",
      options: ["therefore", "despite", "although", "unless"],
      correctIndex: 0,
      explanationVi: "Trạng từ liên kết 'therefore' (do đó) nối hai mệnh đề chỉ quan hệ nguyên nhân - kết quả.",
    },
  ],
  "verb-tense": [
    {
      prompt: "The technician ----- the machine yesterday afternoon.",
      options: ["repairs", "repaired", "has repaired", "will repair"],
      correctIndex: 1,
      explanationVi: "'Yesterday afternoon' là dấu hiệu của thì quá khứ đơn: 'repaired'.",
    },
    {
      prompt: "The company ----- a new product line next month.",
      options: ["launches", "launched", "will launch", "has launched"],
      correctIndex: 2,
      explanationVi: "'Next month' là dấu hiệu của thì tương lai đơn: 'will launch'.",
    },
    {
      prompt: "The accounting department ----- the annual figures at the moment.",
      options: ["reviews", "reviewed", "is reviewing", "has reviewed"],
      correctIndex: 2,
      explanationVi: "'At the moment' là dấu hiệu của thì hiện tại tiếp diễn: 'is reviewing'.",
    },
    {
      prompt: "The consultant ----- with this client for over five years.",
      options: ["works", "worked", "has worked", "is working"],
      correctIndex: 2,
      explanationVi: "'For + khoảng thời gian' đi với thì hiện tại hoàn thành: 'has worked'.",
    },
    {
      prompt: "By the end of this year, the firm ----- over 200 new employees.",
      options: ["will hire", "will have hired", "has hired", "hires"],
      correctIndex: 1,
      explanationVi: "'By + mốc thời gian trong tương lai' đi với thì tương lai hoàn thành: 'will have hired'.",
    },
    {
      prompt: "The IT department ----- the system twice last week.",
      options: ["update", "updated", "updates", "has updated"],
      correctIndex: 1,
      explanationVi: "'Last week' là dấu hiệu của thì quá khứ đơn: 'updated'.",
    },
    {
      prompt: "She ----- for this firm since she graduated from university.",
      options: ["works", "worked", "has worked", "is working"],
      correctIndex: 2,
      explanationVi: "'Since' đi với thì hiện tại hoàn thành: 'has worked'.",
    },
    {
      prompt: "The negotiations ----- for over three hours when both sides finally reached an agreement.",
      options: ["continued", "had continued", "have continued", "were continuing"],
      correctIndex: 1,
      explanationVi: "Hành động kéo dài trước một mốc quá khứ khác cần thì quá khứ hoàn thành: 'had continued'.",
    },
    {
      prompt: "By the end of the fiscal year, the company ----- its expansion into three new markets.",
      options: ["completes", "will complete", "will have completed", "completed"],
      correctIndex: 2,
      explanationVi: "'By the end of' + mốc thời gian tương lai đi với thì tương lai hoàn thành: 'will have completed'.",
    },
    {
      prompt: "The new intern ----- three projects since starting last month.",
      options: ["completes", "completed", "has completed", "is completing"],
      correctIndex: 2,
      explanationVi: "'Since starting' là dấu hiệu của thì hiện tại hoàn thành: 'has completed'.",
    },
    {
      prompt: "Currently, the finance team ----- next year's budget projections.",
      options: ["prepare", "prepared", "is preparing", "has prepared"],
      correctIndex: 2,
      explanationVi: "'Currently' là dấu hiệu của thì hiện tại tiếp diễn: 'is preparing'.",
    },
    {
      prompt: "The vendor ----- the shipment before the storm delayed all deliveries.",
      options: ["sent", "had sent", "has sent", "sends"],
      correctIndex: 1,
      explanationVi: "Hành động hoàn tất trước một sự việc quá khứ khác cần thì quá khứ hoàn thành: 'had sent'.",
    },
    {
      prompt: "Every year, the company ----- its annual report in early March.",
      options: ["publish", "publishes", "published", "is publishing"],
      correctIndex: 1,
      explanationVi: "Hành động lặp lại theo thói quen cần thì hiện tại đơn: 'publishes'.",
    },
  ],
  "passive-voice": [
    {
      prompt: "New employees ----- orientation training during their first week.",
      options: ["give", "are given", "gave", "giving"],
      correctIndex: 1,
      explanationVi: "'Employees' là đối tượng nhận hành động 'give' nên cần bị động hiện tại đơn: 'are given'.",
    },
    {
      prompt: "The conference room ----- last weekend for the renovation.",
      options: ["closed", "was closed", "has closed", "closes"],
      correctIndex: 1,
      explanationVi: "'Conference room' là vật bị đóng, kết hợp với 'last weekend' cần bị động quá khứ đơn: 'was closed'.",
    },
    {
      prompt: "The security system ----- since the break-in last month.",
      options: ["has upgraded", "has been upgraded", "upgraded", "is upgrading"],
      correctIndex: 1,
      explanationVi: "'Since' + mốc thời gian cần bị động hiện tại hoàn thành: 'has been upgraded'.",
    },
    {
      prompt: "All expense reports ----- with receipts attached.",
      options: ["must submit", "must be submitted", "must submitting", "must submitted"],
      correctIndex: 1,
      explanationVi: "Modal 'must' kết hợp với bị động: 'must be submitted'.",
    },
    {
      prompt: "The new headquarters ----- by an award-winning architecture firm at present.",
      options: ["designs", "is designing", "is being designed", "was designed"],
      correctIndex: 2,
      explanationVi: "'At present' cùng chủ ngữ là vật bị tác động cần bị động tiếp diễn: 'is being designed'.",
    },
    {
      prompt: "The final decision ----- by the board next Thursday.",
      options: ["makes", "will make", "will be made", "is making"],
      correctIndex: 2,
      explanationVi: "'Decision' là vật bị đưa ra, kết hợp mốc tương lai cần bị động tương lai: 'will be made'.",
    },
    {
      prompt: "The new regulations ----- reviewed by the legal department at this time.",
      options: ["are being", "are", "is being", "were"],
      correctIndex: 0,
      explanationVi: "Chủ ngữ số nhiều 'regulations' kết hợp 'at this time' cần bị động tiếp diễn: 'are being'.",
    },
    {
      prompt: "All packages ----- carefully before shipment.",
      options: ["inspect", "are inspected", "inspecting", "inspects"],
      correctIndex: 1,
      explanationVi: "Hành động thường lệ, bị động hiện tại đơn: 'are inspected'.",
    },
    {
      prompt: "The contract ----- by both parties before it becomes valid.",
      options: ["must sign", "must be signed", "must signed", "must signing"],
      correctIndex: 1,
      explanationVi: "Modal 'must' kết hợp bị động: 'must be signed'.",
    },
    {
      prompt: "The award ----- to the top-performing employee at last year's ceremony.",
      options: ["gave", "was given", "has given", "gives"],
      correctIndex: 1,
      explanationVi: "'Last year' là dấu hiệu quá khứ đơn, kết hợp bị động: 'was given'.",
    },
    {
      prompt: "The proposal had already ----- by the time the committee reconvened.",
      options: ["approved", "been approved", "approve", "approving"],
      correctIndex: 1,
      explanationVi: "'Had already' + bị động: 'been approved' (thì quá khứ hoàn thành bị động).",
    },
    {
      prompt: "Employee performance ----- annually through a formal review process.",
      options: ["evaluate", "evaluates", "is evaluated", "evaluating"],
      correctIndex: 2,
      explanationVi: "Chủ ngữ nhận hành động, thì hiện tại đơn bị động: 'is evaluated'.",
    },
    {
      prompt: "The damaged equipment ----- as soon as replacement parts arrive.",
      options: ["will repair", "will be repaired", "repairs", "repaired"],
      correctIndex: 1,
      explanationVi: "'Equipment' là vật bị sửa, kết hợp tương lai cần bị động tương lai: 'will be repaired'.",
    },
  ],
  gerund: [
    {
      prompt: "The manager avoided ----- any details about the layoffs during the meeting.",
      options: ["mention", "mentioning", "to mention", "mentioned"],
      correctIndex: 1,
      explanationVi: "'Avoid' theo sau bởi gerund: 'avoided mentioning'.",
    },
    {
      prompt: "The technician fixed the server without ----- any data.",
      options: ["lose", "losing", "to lose", "lost"],
      correctIndex: 1,
      explanationVi: "Sau giới từ 'without' cần V-ing: 'losing'.",
    },
    {
      prompt: "----- customer complaints promptly is essential for maintaining a good reputation.",
      options: ["Address", "Addressing", "To address", "Addressed"],
      correctIndex: 1,
      explanationVi: "Danh động từ (gerund) có thể làm chủ ngữ của câu: 'Addressing'.",
    },
    {
      prompt: "The board finished ----- the quarterly budget just before noon.",
      options: ["review", "reviewing", "to review", "reviewed"],
      correctIndex: 1,
      explanationVi: "'Finish' theo sau bởi gerund: 'finished reviewing'.",
    },
    {
      prompt: "The new hire is responsible for ----- the weekly inventory report.",
      options: ["compile", "compiling", "to compile", "compiled"],
      correctIndex: 1,
      explanationVi: "Sau giới từ trong collocation 'responsible for' cần V-ing: 'compiling'.",
    },
    {
      prompt: "The manager postponed ----- the new policy until next quarter.",
      options: ["announce", "announcing", "to announce", "announced"],
      correctIndex: 1,
      explanationVi: "'Postpone' theo sau bởi gerund: 'postponed announcing'.",
    },
    {
      prompt: "----- overtime hours is common during the busy season.",
      options: ["Work", "Working", "To work", "Worked"],
      correctIndex: 1,
      explanationVi: "Danh động từ làm chủ ngữ của câu: 'Working'.",
    },
    {
      prompt: "The firm is considering ----- its operations to a larger facility.",
      options: ["move", "moving", "to move", "moved"],
      correctIndex: 1,
      explanationVi: "'Consider' theo sau bởi gerund: 'considering moving'.",
    },
    {
      prompt: "Thank you for ----- our invitation to the annual conference.",
      options: ["accept", "accepting", "to accept", "accepted"],
      correctIndex: 1,
      explanationVi: "Sau giới từ 'for' cần V-ing: 'accepting'.",
    },
    {
      prompt: "The supervisor keeps ----- the same mistake in the report.",
      options: ["find", "finding", "to find", "found"],
      correctIndex: 1,
      explanationVi: "'Keep' theo sau bởi gerund: 'keeps finding'.",
    },
    {
      prompt: "Instead of ----- the meeting, the manager sent a written summary.",
      options: ["hold", "holding", "to hold", "held"],
      correctIndex: 1,
      explanationVi: "Sau giới từ 'instead of' cần V-ing: 'holding'.",
    },
    {
      prompt: "The team is looking forward to ----- the new office space next month.",
      options: ["move", "moving", "to move", "moved"],
      correctIndex: 1,
      explanationVi: "'Look forward to' — 'to' ở đây là giới từ, theo sau cần V-ing: 'moving'.",
    },
    {
      prompt: "The auditor recommended ----- the accounting procedures immediately.",
      options: ["revise", "revising", "to revise", "revised"],
      correctIndex: 1,
      explanationVi: "'Recommend' theo sau bởi gerund: 'recommended revising'.",
    },
  ],
  infinitive: [
    {
      prompt: "The director wants ----- the new marketing campaign by next Monday.",
      options: ["launch", "launching", "to launch", "launched"],
      correctIndex: 2,
      explanationVi: "'Want' theo sau bởi to-infinitive: 'wants to launch'.",
    },
    {
      prompt: "The manager was ready ----- the final decision after reviewing all proposals.",
      options: ["make", "making", "to make", "made"],
      correctIndex: 2,
      explanationVi: "Tính từ 'ready' theo sau bởi to-infinitive: 'ready to make'.",
    },
    {
      prompt: "The team scheduled an extra meeting ----- the budget concerns before the deadline.",
      options: ["discussing", "to discuss", "discuss", "discussed"],
      correctIndex: 1,
      explanationVi: "To-infinitive diễn tả mục đích: 'to discuss' (để thảo luận).",
    },
    {
      prompt: "The candidate's experience was strong enough ----- the interview panel.",
      options: ["impress", "impressing", "to impress", "impressed"],
      correctIndex: 2,
      explanationVi: "Cấu trúc 'enough to' luôn dùng to-infinitive: 'to impress'.",
    },
    {
      prompt: "The supervisor asked the interns ----- the survey results before Friday.",
      options: ["summarize", "summarizing", "to summarize", "summarized"],
      correctIndex: 2,
      explanationVi: "Cấu trúc 'ask + tân ngữ + to-infinitive': 'asked the interns to summarize'.",
    },
    {
      prompt: "The company agreed ----- additional compensation to affected customers.",
      options: ["offer", "offering", "to offer", "offered"],
      correctIndex: 2,
      explanationVi: "'Agree' theo sau bởi to-infinitive: 'agreed to offer'.",
    },
    {
      prompt: "It is important ----- all safety procedures during the tour.",
      options: ["follow", "following", "to follow", "followed"],
      correctIndex: 2,
      explanationVi: "Cấu trúc 'It is + tính từ + to-infinitive': 'important to follow'.",
    },
    {
      prompt: "The manager promised ----- the issue by the end of the week.",
      options: ["resolve", "resolving", "to resolve", "resolved"],
      correctIndex: 2,
      explanationVi: "'Promise' theo sau bởi to-infinitive: 'promised to resolve'.",
    },
    {
      prompt: "The staff arrived early ----- for the client's visit.",
      options: ["prepare", "preparing", "to prepare", "prepared"],
      correctIndex: 2,
      explanationVi: "To-infinitive diễn tả mục đích: 'to prepare' (để chuẩn bị).",
    },
    {
      prompt: "The applicant failed ----- all required documents.",
      options: ["submit", "submitting", "to submit", "submitted"],
      correctIndex: 2,
      explanationVi: "'Fail' theo sau bởi to-infinitive: 'failed to submit'.",
    },
    {
      prompt: "The new system is designed ----- processing time significantly.",
      options: ["reduce", "reducing", "to reduce", "reduced"],
      correctIndex: 2,
      explanationVi: "Cấu trúc 'designed + to-infinitive': 'designed to reduce'.",
    },
    {
      prompt: "Employees are encouraged ----- feedback through the online portal.",
      options: ["provide", "providing", "to provide", "provided"],
      correctIndex: 2,
      explanationVi: "Cấu trúc bị động 'be encouraged + to-infinitive': 'encouraged to provide'.",
    },
  ],
  "relative-clause": [
    {
      prompt: "The candidate ----- impressed the interview panel was offered the position immediately.",
      options: ["who", "which", "whose", "whom"],
      correctIndex: 0,
      explanationVi: "'Who' làm chủ ngữ của mệnh đề quan hệ chỉ người.",
    },
    {
      prompt: "The new policy, ----- takes effect next month, will affect all departments.",
      options: ["who", "which", "that", "whose"],
      correctIndex: 1,
      explanationVi: "Mệnh đề quan hệ không xác định (có dấu phẩy) chỉ vật dùng 'which', không dùng 'that'.",
    },
    {
      prompt: "Mr. Lee, ----- the board recently promoted, will oversee the new division.",
      options: ["who", "whom", "whose", "which"],
      correctIndex: 1,
      explanationVi: "'Whom' làm tân ngữ của động từ 'promoted' trong mệnh đề quan hệ chỉ người.",
    },
    {
      prompt: "The report ----- the analyst submitted last week contained several errors.",
      options: ["who", "whom", "that", "whose"],
      correctIndex: 2,
      explanationVi: "'That' làm tân ngữ, thay thế cho danh từ chỉ vật 'the report' trong mệnh đề quan hệ xác định.",
    },
    {
      prompt: "Employees ----- overtime this month will receive additional compensation.",
      options: ["who work", "working", "whom work", "worked"],
      correctIndex: 1,
      explanationVi: "Rút gọn mệnh đề quan hệ chủ động ('who are working') thành cụm phân từ hiện tại: 'working'.",
    },
    {
      prompt: "The supplier ----- products meet our quality standards has been our partner for years.",
      options: ["who", "whose", "which", "whom"],
      correctIndex: 1,
      explanationVi: "'Whose' chỉ sở hữu: sản phẩm của nhà cung cấp đó.",
    },
    {
      prompt: "This is the office ----- the new marketing team will work.",
      options: ["which", "where", "who", "whose"],
      correctIndex: 1,
      explanationVi: "'Where' dùng để chỉ nơi chốn.",
    },
    {
      prompt: "The reason ----- the shipment was delayed is still unclear.",
      options: ["why", "which", "who", "whose"],
      correctIndex: 0,
      explanationVi: "'Why' giới thiệu mệnh đề quan hệ chỉ lý do, sau danh từ 'reason'.",
    },
    {
      prompt: "The engineer ----- designed the system left the company last year.",
      options: ["whom", "whose", "who", "which"],
      correctIndex: 2,
      explanationVi: "'Who' làm chủ ngữ của mệnh đề quan hệ chỉ người.",
    },
    {
      prompt: "The building, ----- was constructed in 1998, is now being renovated.",
      options: ["that", "which", "who", "whose"],
      correctIndex: 1,
      explanationVi: "Mệnh đề quan hệ không xác định (có dấu phẩy) chỉ vật dùng 'which', không dùng 'that'.",
    },
    {
      prompt: "The client ----- order was delayed received a discount on the next purchase.",
      options: ["who", "whom", "whose", "which"],
      correctIndex: 2,
      explanationVi: "'Whose' chỉ sở hữu: đơn hàng của khách hàng đó.",
    },
    {
      prompt: "The candidates ----- résumés impressed the panel were invited for a second interview.",
      options: ["who", "whom", "whose", "which"],
      correctIndex: 2,
      explanationVi: "'Whose' chỉ sở hữu: résumé của các ứng viên đó.",
    },
    {
      prompt: "The documents ----- are required for the audit are stored in the archive.",
      options: ["who", "that", "whose", "whom"],
      correctIndex: 1,
      explanationVi: "'That' làm chủ ngữ của mệnh đề quan hệ xác định, thay thế cho danh từ chỉ vật 'documents'.",
    },
  ],
  conditionals: [
    {
      prompt: "If the weather improves tomorrow, the outdoor event ----- as planned.",
      options: ["proceeds", "will proceed", "would proceed", "proceeded"],
      correctIndex: 1,
      explanationVi: "Câu điều kiện loại 1: mệnh đề chính dùng 'will + V'.",
    },
    {
      prompt: "If an employee ----- late three times, the supervisor issues a formal warning.",
      options: ["arrives", "arrived", "will arrive", "has arrived"],
      correctIndex: 0,
      explanationVi: "Câu điều kiện loại 0 diễn tả sự thật/quy tắc chung: cả hai mệnh đề dùng hiện tại đơn.",
    },
    {
      prompt: "If the company had more funding, it ----- into international markets.",
      options: ["expands", "would expand", "will expand", "expanded"],
      correctIndex: 1,
      explanationVi: "Câu điều kiện loại 2: mệnh đề chính dùng 'would + V'.",
    },
    {
      prompt: "If the manager ----- more time, she would review every application personally.",
      options: ["has", "had", "have", "will have"],
      correctIndex: 1,
      explanationVi: "Câu điều kiện loại 2: mệnh đề if dùng quá khứ đơn 'had'.",
    },
    {
      prompt: "If the technician ----- the machine sooner, the factory would not have lost a full day of production.",
      options: ["repaired", "had repaired", "would repair", "repairs"],
      correctIndex: 1,
      explanationVi: "Câu điều kiện loại 3: mệnh đề if dùng quá khứ hoàn thành 'had repaired'.",
    },
    {
      prompt: "If sales continue to decline, the company ----- to cut costs.",
      options: ["need", "needs", "will need", "would need"],
      correctIndex: 2,
      explanationVi: "Câu điều kiện loại 1: mệnh đề chính dùng 'will + V'.",
    },
    {
      prompt: "If the shipment arrives late, we ----- inform the client immediately.",
      options: ["will", "would", "had", "are"],
      correctIndex: 0,
      explanationVi: "Câu điều kiện loại 1: mệnh đề chính dùng modal 'will'.",
    },
    {
      prompt: "Unless the client approves the design, the project ----- move forward.",
      options: ["will not", "would not", "does not", "did not"],
      correctIndex: 0,
      explanationVi: "'Unless' (= if not) đi với câu điều kiện loại 1: 'will not'.",
    },
    {
      prompt: "If the training program were more interactive, employees ----- more engaged.",
      options: ["are", "were", "would be", "will be"],
      correctIndex: 2,
      explanationVi: "Câu điều kiện loại 2: mệnh đề chính dùng 'would + V'.",
    },
    {
      prompt: "If she ----- about the change earlier, she would have adjusted her schedule.",
      options: ["knew", "had known", "knows", "would know"],
      correctIndex: 1,
      explanationVi: "Câu điều kiện loại 3: mệnh đề if dùng quá khứ hoàn thành 'had known'.",
    },
    {
      prompt: "If the equipment is not maintained regularly, it ----- down frequently.",
      options: ["breaks", "broke", "would break", "will break"],
      correctIndex: 0,
      explanationVi: "Câu điều kiện loại 0 diễn tả sự thật chung: cả hai mệnh đề dùng hiện tại đơn.",
    },
    {
      prompt: "The team would have met the deadline if the data ----- available sooner.",
      options: ["was", "were", "had been", "is"],
      correctIndex: 2,
      explanationVi: "Câu điều kiện loại 3: mệnh đề if dùng quá khứ hoàn thành 'had been'.",
    },
    {
      prompt: "If you ----- any issues, please contact technical support immediately.",
      options: ["encounter", "encountered", "will encounter", "would encounter"],
      correctIndex: 0,
      explanationVi: "Câu điều kiện loại 1: mệnh đề if dùng hiện tại đơn 'encounter'.",
    },
  ],
  comparatives: [
    {
      prompt: "This year's turnout was ----- than last year's.",
      options: ["large", "larger", "largest", "more large"],
      correctIndex: 1,
      explanationVi: "So sánh hơn với tính từ ngắn thêm '-er': 'larger'.",
    },
    {
      prompt: "The updated software is ----- reliable as the previous version.",
      options: ["as", "so", "more", "than"],
      correctIndex: 0,
      explanationVi: "Cấu trúc so sánh bằng: 'as + tính từ + as'.",
    },
    {
      prompt: "Of all the branches, the downtown location is ----- to reach by public transport.",
      options: ["easy", "easier", "the easiest", "more easy"],
      correctIndex: 2,
      explanationVi: "So sánh nhất với tính từ ngắn: 'the easiest', dùng khi so sánh từ ba đối tượng trở lên.",
    },
    {
      prompt: "The updated model is ----- expensive than the previous one, making it more accessible to small businesses.",
      options: ["less", "least", "fewer", "few"],
      correctIndex: 0,
      explanationVi: "Cấu trúc so sánh kém hơn: 'less + tính từ + than'.",
    },
    {
      prompt: "----- more feedback the team receives, the more effective the final product becomes.",
      options: ["The", "A", "Much", "More"],
      correctIndex: 0,
      explanationVi: "Cấu trúc song song 'The + so sánh hơn..., the + so sánh hơn...' diễn tả hai sự việc tăng/giảm cùng nhau.",
    },
    {
      prompt: "The new model runs ----- than the previous version.",
      options: ["quiet", "quieter", "quietest", "more quiet"],
      correctIndex: 1,
      explanationVi: "So sánh hơn với tính từ ngắn thêm '-er': 'quieter'.",
    },
    {
      prompt: "This branch generates ----- revenue of all the locations in the region.",
      options: ["high", "higher", "the highest", "more high"],
      correctIndex: 2,
      explanationVi: "So sánh nhất khi so sánh từ ba đối tượng trở lên: 'the highest'.",
    },
    {
      prompt: "The client's second proposal was ----- appealing than the first.",
      options: ["less", "least", "fewer", "few"],
      correctIndex: 0,
      explanationVi: "So sánh kém hơn giữa hai đối tượng: 'less + tính từ + than'.",
    },
    {
      prompt: "The negotiations took ----- time than anyone had expected.",
      options: ["much", "many", "more", "most"],
      correctIndex: 2,
      explanationVi: "So sánh hơn với danh từ không đếm được 'time': 'more time'.",
    },
    {
      prompt: "----- employees are trained, the more efficient the department becomes.",
      options: ["The more", "More", "Much more", "The most"],
      correctIndex: 0,
      explanationVi: "Cấu trúc song song 'The more..., the more...' diễn tả hai sự việc tăng cùng nhau.",
    },
    {
      prompt: "Of the two candidates, Ms. Pham has ----- experience in project management.",
      options: ["more", "most", "the more", "much"],
      correctIndex: 0,
      explanationVi: "'Of the two' báo hiệu so sánh hơn giữa hai đối tượng: 'more'.",
    },
    {
      prompt: "The updated policy is ----- straightforward as the original one, causing less confusion.",
      options: ["more", "most", "as", "less"],
      correctIndex: 2,
      explanationVi: "Cấu trúc so sánh bằng: 'as + tính từ + as'.",
    },
    {
      prompt: "This is by far the ----- effective marketing strategy the team has used.",
      options: ["more", "most", "much", "very"],
      correctIndex: 1,
      explanationVi: "So sánh nhất: 'the most effective', nhấn mạnh thêm bằng 'by far'.",
    },
  ],
  "subject-verb-agreement": [
    {
      prompt: "Each member of the committee ----- required to submit a report.",
      options: ["is", "are", "were", "have been"],
      correctIndex: 0,
      explanationVi: "'Each + danh từ số ít' luôn đi với động từ số ít: 'is'.",
    },
    {
      prompt: "The research team ----- currently analyzing the survey results.",
      options: ["is", "are", "were", "have"],
      correctIndex: 0,
      explanationVi: "Danh từ tập hợp 'team' được coi là số ít trong tiếng Anh trang trọng: 'is'.",
    },
    {
      prompt: "The number of complaints ----- decreased significantly this quarter.",
      options: ["has", "have", "were", "are"],
      correctIndex: 0,
      explanationVi: "'The number of' + danh từ số nhiều nhưng đi với động từ số ít: 'has'.",
    },
    {
      prompt: "Neither the manager nor the assistants ----- available to attend the call.",
      options: ["is", "are", "was", "has"],
      correctIndex: 1,
      explanationVi: "Với 'neither...nor', động từ hòa hợp với chủ ngữ gần nó nhất ('the assistants' - số nhiều): 'are'.",
    },
    {
      prompt: "Enclosed with this letter ----- the documents you requested.",
      options: ["is", "are", "was", "has"],
      correctIndex: 1,
      explanationVi: "Câu đảo ngữ có chủ ngữ thực sự là 'the documents' (số nhiều) đứng sau động từ: 'are'.",
    },
    {
      prompt: "Every employee and manager ----- required to attend the safety briefing.",
      options: ["is", "are", "were", "have been"],
      correctIndex: 0,
      explanationVi: "'Every...and...' vẫn được coi là số ít: 'is'.",
    },
    {
      prompt: "The information provided in the documents ----- accurate.",
      options: ["is", "are", "were", "have been"],
      correctIndex: 0,
      explanationVi: "'Information' là danh từ không đếm được, luôn đi với động từ số ít: 'is'.",
    },
    {
      prompt: "Either the supervisor or the team members ----- responsible for submitting the report.",
      options: ["is", "are", "was", "has"],
      correctIndex: 1,
      explanationVi: "Với 'either...or', động từ hòa hợp với chủ ngữ gần nó nhất ('team members' - số nhiều): 'are'.",
    },
    {
      prompt: "The committee members ----- divided on the proposed changes.",
      options: ["is", "are", "was", "has been"],
      correctIndex: 1,
      explanationVi: "'Committee members' rõ ràng ở dạng số nhiều: 'are'.",
    },
    {
      prompt: "Economics ----- one of the required courses for the program.",
      options: ["is", "are", "were", "have"],
      correctIndex: 0,
      explanationVi: "Tên môn học tận cùng bằng '-ics' (economics, mathematics) được coi là số ít: 'is'.",
    },
    {
      prompt: "Most of the equipment in the lab ----- outdated.",
      options: ["is", "are", "were", "have been"],
      correctIndex: 0,
      explanationVi: "'Equipment' là danh từ không đếm được số ít; 'most of' hòa hợp theo danh từ theo sau: 'is'.",
    },
    {
      prompt: "The board, as well as the shareholders, ----- expected to approve the merger.",
      options: ["is", "are", "were", "have"],
      correctIndex: 0,
      explanationVi: "Cụm 'as well as...' không làm chủ ngữ chính 'the board' (số ít) thành số nhiều: 'is'.",
    },
    {
      prompt: "There ----- several reasons why the launch was delayed.",
      options: ["is", "are", "was", "has been"],
      correctIndex: 1,
      explanationVi: "'There + be' hòa hợp với danh từ thực sự theo sau ('reasons' - số nhiều): 'are'.",
    },
  ],
  participles: [
    {
      prompt: "The ----- documents should be filed in the cabinet by end of day.",
      options: ["complete", "completing", "completed", "completion"],
      correctIndex: 2,
      explanationVi: "'Documents' bị hoàn thành nên dùng phân từ quá khứ mang nghĩa bị động: 'completed'.",
    },
    {
      prompt: "The seminar covered several ----- issues affecting small businesses today.",
      options: ["challenge", "challenging", "challenged", "challenges"],
      correctIndex: 1,
      explanationVi: "'Issues' chủ động gây ra thách thức nên dùng phân từ hiện tại: 'challenging'.",
    },
    {
      prompt: "----- for over a decade, the machine finally needs to be replaced.",
      options: ["Use", "Using", "Used", "To use"],
      correctIndex: 2,
      explanationVi: "Cụm phân từ rút gọn từ mệnh đề bị động ('which has been used'), dùng phân từ quá khứ 'Used' đứng đầu câu.",
    },
    {
      prompt: "----- the quarterly figures carefully, the auditor identified several discrepancies.",
      options: ["Review", "Reviewing", "Reviewed", "To review"],
      correctIndex: 1,
      explanationVi: "Cụm phân từ chủ động rút gọn từ mệnh đề 'As the auditor reviewed...', chủ ngữ của cụm phân từ trùng với chủ ngữ chính: 'Reviewing'.",
    },
    {
      prompt: "Investors expressed interest in the company's ----- plan to expand overseas operations.",
      options: ["propose", "proposing", "proposed", "proposal"],
      correctIndex: 2,
      explanationVi: "'Plan' là kế hoạch được đề xuất (bị động) nên dùng phân từ quá khứ: 'proposed'.",
    },
    {
      prompt: "The ----- staff will receive a bonus at the end of the year.",
      options: ["remain", "remaining", "remained", "remainder"],
      correctIndex: 1,
      explanationVi: "'Remaining staff' (nhân viên còn lại) dùng phân từ hiện tại mang nghĩa mô tả.",
    },
    {
      prompt: "----- with the results, the manager approved the next phase of the project.",
      options: ["Satisfy", "Satisfying", "Satisfied", "Satisfaction"],
      correctIndex: 2,
      explanationVi: "Cụm phân từ đầu câu mang nghĩa bị động (người quản lý cảm thấy hài lòng): 'Satisfied'.",
    },
    {
      prompt: "The report contains ----- data collected over the past five years.",
      options: ["detail", "detailing", "detailed", "details"],
      correctIndex: 2,
      explanationVi: "Trước danh từ 'data' cần phân từ quá khứ mang nghĩa mô tả: 'detailed'.",
    },
    {
      prompt: "----- by the sudden increase in orders, the production managers hired additional staff.",
      options: ["Overwhelm", "Overwhelming", "Overwhelmed", "Overwhelms"],
      correctIndex: 2,
      explanationVi: "Cụm phân từ đầu câu mang nghĩa bị động (các quản lý cảm thấy quá tải): 'Overwhelmed'.",
    },
    {
      prompt: "Employees ----- in the pilot program will receive additional training.",
      options: ["participate", "participating", "participated", "participation"],
      correctIndex: 1,
      explanationVi: "Rút gọn từ 'who are participating' thành cụm phân từ hiện tại chủ động: 'participating'.",
    },
    {
      prompt: "The manual includes step-by-step instructions ----- to help new users.",
      options: ["design", "designing", "designed", "designs"],
      correctIndex: 2,
      explanationVi: "'Instructions' bị thiết kế (bị động) nên dùng phân từ quá khứ: 'designed'.",
    },
    {
      prompt: "----- the client's concerns, the sales team revised the proposal.",
      options: ["Address", "Addressing", "Addressed", "Address's"],
      correctIndex: 1,
      explanationVi: "Cụm phân từ chủ động đầu câu (đội bán hàng chủ động giải quyết): 'Addressing'.",
    },
    {
      prompt: "The ----- number of applicants exceeded the company's expectations.",
      options: ["surprise", "surprising", "surprised", "surprisingly"],
      correctIndex: 1,
      explanationVi: "Trước danh từ 'number' cần phân từ hiện tại mang nghĩa 'đáng ngạc nhiên': 'surprising'.",
    },
  ],
};
