export interface SeedWord {
  word: string;
  ipa: string;
  partOfSpeech: string;
  meaningVi: string;
  definitionEn: string;
  exampleEn: string;
  exampleVi: string;
  synonyms?: string[];
  collocations?: string[];
  difficulty?: "EASY" | "MEDIUM" | "HARD";
}

export interface SeedVocabularyTopic {
  slug: string;
  name: string;
  description: string;
  category: string;
  words: SeedWord[];
}

export const VOCABULARY_TOPICS_BAND: SeedVocabularyTopic[] = [
  {
    slug: "band-300",
    name: "TOEIC 300+",
    description: "Từ vựng nền tảng, thông dụng nhất cần nắm để đạt mốc 300 điểm.",
    category: "Theo band điểm",
    words: [
      { word: "company", ipa: "ˈkʌmpəni", partOfSpeech: "noun", meaningVi: "công ty", definitionEn: "A business organization that sells goods or services.", exampleEn: "He has worked for this company for three years.", exampleVi: "Anh ấy đã làm việc cho công ty này được ba năm.", difficulty: "EASY" },
      { word: "employee", ipa: "ɪmˈplɔɪiː", partOfSpeech: "noun", meaningVi: "nhân viên", definitionEn: "A person who works for a company in exchange for pay.", exampleEn: "Every employee must wear an ID badge at work.", exampleVi: "Mọi nhân viên đều phải đeo thẻ tên khi làm việc.", synonyms: ["worker", "staff member"], difficulty: "EASY" },
      { word: "customer", ipa: "ˈkʌstəmər", partOfSpeech: "noun", meaningVi: "khách hàng", definitionEn: "A person who buys goods or services from a business.", exampleEn: "The store stays open late to serve more customers.", exampleVi: "Cửa hàng mở cửa muộn hơn để phục vụ thêm khách hàng.", synonyms: ["client"], difficulty: "EASY" },
      { word: "buy", ipa: "baɪ", partOfSpeech: "verb", meaningVi: "mua", definitionEn: "To obtain something by paying money for it.", exampleEn: "I need to buy a new printer for the office.", exampleVi: "Tôi cần mua một chiếc máy in mới cho văn phòng.", synonyms: ["purchase"], difficulty: "EASY" },
      { word: "sell", ipa: "sɛl", partOfSpeech: "verb", meaningVi: "bán", definitionEn: "To give something to someone in exchange for money.", exampleEn: "This shop sells office furniture at low prices.", exampleVi: "Cửa hàng này bán đồ nội thất văn phòng với giá thấp.", difficulty: "EASY" },
      { word: "cheap", ipa: "tʃiːp", partOfSpeech: "adjective", meaningVi: "rẻ", definitionEn: "Costing very little money.", exampleEn: "The new supplier offers cheap but good quality paper.", exampleVi: "Nhà cung cấp mới bán giấy với giá rẻ nhưng chất lượng tốt.", difficulty: "EASY" },
      { word: "expensive", ipa: "ɪkˈspɛnsɪv", partOfSpeech: "adjective", meaningVi: "đắt", definitionEn: "Costing a lot of money.", exampleEn: "That laptop is too expensive for our budget.", exampleVi: "Chiếc laptop đó quá đắt so với ngân sách của chúng tôi.", difficulty: "EASY" },
      { word: "job", ipa: "dʒɒb", partOfSpeech: "noun", meaningVi: "công việc", definitionEn: "The regular work a person does to earn money.", exampleEn: "She started a new job at the bank last month.", exampleVi: "Cô ấy bắt đầu công việc mới ở ngân hàng vào tháng trước.", difficulty: "EASY" },
      { word: "salary", ipa: "ˈsæləri", partOfSpeech: "noun", meaningVi: "lương", definitionEn: "The money a person is paid regularly for their work.", exampleEn: "Employees receive their salary on the last day of the month.", exampleVi: "Nhân viên nhận lương vào ngày cuối cùng của tháng.", difficulty: "EASY" },
      { word: "answer", ipa: "ˈænsər", partOfSpeech: "verb", meaningVi: "trả lời", definitionEn: "To reply to a question or a phone call.", exampleEn: "Please answer the phone if it rings while I'm out.", exampleVi: "Vui lòng trả lời điện thoại nếu nó reo khi tôi ra ngoài.", difficulty: "EASY" },
      { word: "arrive", ipa: "əˈraɪv", partOfSpeech: "verb", meaningVi: "đến nơi", definitionEn: "To reach a place after traveling.", exampleEn: "The delivery truck will arrive at nine in the morning.", exampleVi: "Xe giao hàng sẽ đến vào chín giờ sáng.", difficulty: "EASY" },
      { word: "leave", ipa: "liːv", partOfSpeech: "verb", meaningVi: "rời đi", definitionEn: "To go away from a place.", exampleEn: "Most staff leave the office by six o'clock.", exampleVi: "Hầu hết nhân viên rời văn phòng lúc sáu giờ.", difficulty: "EASY" },
      { word: "receipt", ipa: "rɪˈsiːt", partOfSpeech: "noun", meaningVi: "biên lai, hóa đơn", definitionEn: "A printed paper showing that money was paid.", exampleEn: "Keep your receipt in case you need to return the item.", exampleVi: "Hãy giữ biên lai phòng khi bạn cần trả lại món hàng.", difficulty: "EASY" },
      { word: "borrow", ipa: "ˈbɒroʊ", partOfSpeech: "verb", meaningVi: "mượn", definitionEn: "To take and use something that belongs to someone else, planning to return it.", exampleEn: "Can I borrow your pen for a minute?", exampleVi: "Tôi có thể mượn cây bút của bạn một lát không?", difficulty: "EASY" },
      { word: "repair", ipa: "rɪˈpɛər", partOfSpeech: "verb", meaningVi: "sửa chữa", definitionEn: "To fix something that is broken or damaged.", exampleEn: "A technician came to repair the copy machine.", exampleVi: "Một kỹ thuật viên đã đến sửa chữa máy photocopy.", synonyms: ["fix"], difficulty: "EASY" },
      { word: "empty", ipa: "ˈɛmpti", partOfSpeech: "adjective", meaningVi: "trống, rỗng", definitionEn: "Containing nothing or no people.", exampleEn: "The meeting room next to mine is usually empty in the morning.", exampleVi: "Phòng họp cạnh phòng tôi thường trống vào buổi sáng.", difficulty: "EASY" },
      { word: "form", ipa: "fɔːrm", partOfSpeech: "noun", meaningVi: "biểu mẫu", definitionEn: "A printed document with blank spaces to be filled in with information.", exampleEn: "Please fill out this form before your appointment.", exampleVi: "Vui lòng điền vào biểu mẫu này trước cuộc hẹn của bạn.", difficulty: "EASY" },
      { word: "wait", ipa: "weɪt", partOfSpeech: "verb", meaningVi: "chờ đợi", definitionEn: "To stay in a place until something happens.", exampleEn: "Visitors should wait in the lobby until they are called.", exampleVi: "Khách nên chờ ở sảnh cho đến khi được gọi tên.", difficulty: "EASY" },
    ],
  },
  {
    slug: "band-500",
    name: "TOEIC 500+",
    description: "Từ vựng thiết yếu cho mốc 500 điểm, tập trung vào ngữ cảnh công sở và đời sống.",
    category: "Theo band điểm",
    words: [
      { word: "confirm", ipa: "kənˈfɜːrm", partOfSpeech: "verb", meaningVi: "xác nhận", definitionEn: "To state that something is true or correct.", exampleEn: "Please confirm your attendance by replying to this email.", exampleVi: "Vui lòng xác nhận tham dự bằng cách trả lời email này.", difficulty: "EASY" },
      { word: "available", ipa: "əˈveɪləbəl", partOfSpeech: "adjective", meaningVi: "có sẵn, rảnh", definitionEn: "Able to be used or obtained; free to do something.", exampleEn: "The manager is available for a call after lunch.", exampleVi: "Quản lý sẽ rảnh để gọi điện sau bữa trưa.", difficulty: "EASY" },
      { word: "require", ipa: "rɪˈkwaɪər", partOfSpeech: "verb", meaningVi: "yêu cầu, đòi hỏi", definitionEn: "To need something or make something necessary.", exampleEn: "This position requires at least two years of experience.", exampleVi: "Vị trí này yêu cầu ít nhất hai năm kinh nghiệm.", synonyms: ["need"], difficulty: "MEDIUM" },
      { word: "renew", ipa: "rɪˈnuː", partOfSpeech: "verb", meaningVi: "gia hạn", definitionEn: "To extend the period of validity of something.", exampleEn: "Remember to renew your parking permit before it expires.", exampleVi: "Hãy nhớ gia hạn thẻ đỗ xe trước khi nó hết hạn.", difficulty: "MEDIUM" },
      { word: "arrange", ipa: "əˈreɪndʒ", partOfSpeech: "verb", meaningVi: "sắp xếp, thu xếp", definitionEn: "To plan or organize something in advance.", exampleEn: "Our assistant will arrange the flight and hotel for the trip.", exampleVi: "Trợ lý của chúng tôi sẽ thu xếp vé máy bay và khách sạn cho chuyến đi.", collocations: ["arrange a meeting", "arrange transportation"], difficulty: "MEDIUM" },
      { word: "notify", ipa: "ˈnoʊtɪfaɪ", partOfSpeech: "verb", meaningVi: "thông báo", definitionEn: "To formally inform someone of something.", exampleEn: "Staff will be notified of the schedule change by email.", exampleVi: "Nhân viên sẽ được thông báo về thay đổi lịch trình qua email.", synonyms: ["inform"], difficulty: "MEDIUM" },
      { word: "estimate", ipa: "ˈɛstɪmeɪt", partOfSpeech: "verb", meaningVi: "ước tính", definitionEn: "To roughly calculate the value, size, or cost of something.", exampleEn: "The contractor estimated the repairs would cost $500.", exampleVi: "Nhà thầu ước tính việc sửa chữa sẽ tốn 500 đô la.", difficulty: "MEDIUM" },
      { word: "quality", ipa: "ˈkwɒlɪti", partOfSpeech: "noun", meaningVi: "chất lượng", definitionEn: "The standard of something as measured against other similar things.", exampleEn: "The factory checks the quality of every product before shipping.", exampleVi: "Nhà máy kiểm tra chất lượng từng sản phẩm trước khi giao hàng.", difficulty: "EASY" },
      { word: "shortage", ipa: "ˈʃɔːrtɪdʒ", partOfSpeech: "noun", meaningVi: "sự thiếu hụt", definitionEn: "A situation in which there is not enough of something.", exampleEn: "The restaurant is facing a shortage of kitchen staff.", exampleVi: "Nhà hàng đang thiếu hụt nhân viên bếp.", difficulty: "MEDIUM" },
      { word: "replace", ipa: "rɪˈpleɪs", partOfSpeech: "verb", meaningVi: "thay thế", definitionEn: "To put a new or different thing in the place of something.", exampleEn: "We need to replace the old printer in the office.", exampleVi: "Chúng tôi cần thay thế chiếc máy in cũ trong văn phòng.", difficulty: "EASY" },
      { word: "attach", ipa: "əˈtætʃ", partOfSpeech: "verb", meaningVi: "đính kèm", definitionEn: "To fasten or connect one thing to another.", exampleEn: "I attached the invoice to this email for your reference.", exampleVi: "Tôi đã đính kèm hóa đơn vào email này để bạn tham khảo.", difficulty: "EASY" },
      { word: "approve", ipa: "əˈpruːv", partOfSpeech: "verb", meaningVi: "phê duyệt", definitionEn: "To officially agree to or accept something as satisfactory.", exampleEn: "The director must approve all purchases over $1,000.", exampleVi: "Giám đốc phải phê duyệt mọi khoản mua sắm trên 1.000 đô la.", collocations: ["approve a request", "approve a budget"], difficulty: "MEDIUM" },
      { word: "distribute", ipa: "dɪˈstrɪbjuːt", partOfSpeech: "verb", meaningVi: "phân phát, phân phối", definitionEn: "To give or deliver something to a number of people or places.", exampleEn: "Handouts will be distributed at the start of the seminar.", exampleVi: "Tài liệu sẽ được phát cho mọi người vào đầu buổi hội thảo.", difficulty: "MEDIUM" },
      { word: "supply", ipa: "səˈplaɪ", partOfSpeech: "noun", meaningVi: "nguồn cung, việc cung cấp", definitionEn: "The amount of something available for use, or the act of providing it.", exampleEn: "The company signed a new contract for the supply of office paper.", exampleVi: "Công ty đã ký hợp đồng mới về cung cấp giấy văn phòng.", difficulty: "MEDIUM" },
      { word: "regulation", ipa: "ˌrɛɡjəˈleɪʃən", partOfSpeech: "noun", meaningVi: "quy định", definitionEn: "An official rule made by an authority.", exampleEn: "All employees must follow the new safety regulations.", exampleVi: "Mọi nhân viên phải tuân theo các quy định an toàn mới.", synonyms: ["rule"], difficulty: "MEDIUM" },
      { word: "renovate", ipa: "ˈrɛnəveɪt", partOfSpeech: "verb", meaningVi: "cải tạo, tu sửa", definitionEn: "To repair and improve a building so it is in good condition again.", exampleEn: "The head office will be renovated over the summer.", exampleVi: "Trụ sở chính sẽ được cải tạo trong mùa hè.", difficulty: "MEDIUM" },
      { word: "punctual", ipa: "ˈpʌŋktʃuəl", partOfSpeech: "adjective", meaningVi: "đúng giờ", definitionEn: "Arriving or doing something at the expected time.", exampleEn: "Employees are expected to be punctual for every shift.", exampleVi: "Nhân viên được yêu cầu phải đúng giờ trong mỗi ca làm việc.", difficulty: "MEDIUM" },
      { word: "convenient", ipa: "kənˈviːniənt", partOfSpeech: "adjective", meaningVi: "thuận tiện", definitionEn: "Suited to one's needs or making something easy to do.", exampleEn: "The new office location is more convenient for most staff.", exampleVi: "Địa điểm văn phòng mới thuận tiện hơn cho hầu hết nhân viên.", difficulty: "EASY" },
    ],
  },
  {
    slug: "band-700",
    name: "TOEIC 700+",
    description: "Từ vựng nâng cao cho mốc 700 điểm, đa dạng ngữ cảnh kinh doanh.",
    category: "Theo band điểm",
    words: [
      { word: "implement", ipa: "ˈɪmplɪmɛnt", partOfSpeech: "verb", meaningVi: "thực thi, triển khai", definitionEn: "To put a plan or decision into effect.", exampleEn: "The firm will implement the new policy starting next quarter.", exampleVi: "Công ty sẽ triển khai chính sách mới kể từ quý tới.", collocations: ["implement a policy", "implement changes"], difficulty: "MEDIUM" },
      { word: "allocate", ipa: "ˈæləkeɪt", partOfSpeech: "verb", meaningVi: "phân bổ", definitionEn: "To officially give a share of money or resources for a particular purpose.", exampleEn: "The board allocated additional funds to the research division.", exampleVi: "Hội đồng quản trị đã phân bổ thêm ngân sách cho bộ phận nghiên cứu.", difficulty: "MEDIUM" },
      { word: "streamline", ipa: "ˈstriːmlaɪn", partOfSpeech: "verb", meaningVi: "hợp lý hóa, tinh gọn", definitionEn: "To make a process simpler and more efficient.", exampleEn: "Management is streamlining the approval process to save time.", exampleVi: "Ban quản lý đang tinh gọn quy trình phê duyệt để tiết kiệm thời gian.", difficulty: "MEDIUM" },
      { word: "viable", ipa: "ˈvaɪəbəl", partOfSpeech: "adjective", meaningVi: "khả thi", definitionEn: "Capable of working successfully; feasible.", exampleEn: "The team is looking for a more viable solution to the delay.", exampleVi: "Nhóm đang tìm một giải pháp khả thi hơn cho sự chậm trễ.", synonyms: ["feasible"], difficulty: "MEDIUM" },
      { word: "comprehensive", ipa: "ˌkɒmprɪˈhɛnsɪv", partOfSpeech: "adjective", meaningVi: "toàn diện", definitionEn: "Including all or nearly all elements of something.", exampleEn: "The consultant provided a comprehensive review of our operations.", exampleVi: "Chuyên gia tư vấn đã cung cấp một đánh giá toàn diện về hoạt động của chúng tôi.", difficulty: "MEDIUM" },
      { word: "prioritize", ipa: "praɪˈɔːrɪtaɪz", partOfSpeech: "verb", meaningVi: "ưu tiên", definitionEn: "To treat something as more important than other things.", exampleEn: "We need to prioritize customer complaints over routine tasks today.", exampleVi: "Hôm nay chúng ta cần ưu tiên xử lý khiếu nại của khách hàng hơn các việc thường ngày.", difficulty: "MEDIUM" },
      { word: "surplus", ipa: "ˈsɜːrplʌs", partOfSpeech: "noun", meaningVi: "thặng dư, phần dư thừa", definitionEn: "An amount of something left over after requirements have been met.", exampleEn: "The warehouse has a surplus of last season's inventory.", exampleVi: "Nhà kho có phần hàng tồn dư thừa từ mùa trước.", difficulty: "MEDIUM" },
      { word: "liability", ipa: "ˌlaɪəˈbɪləti", partOfSpeech: "noun", meaningVi: "trách nhiệm pháp lý, nghĩa vụ nợ", definitionEn: "A legal responsibility, or a debt owed by a company.", exampleEn: "The contract limits the supplier's liability for shipping delays.", exampleVi: "Hợp đồng giới hạn trách nhiệm pháp lý của nhà cung cấp đối với việc giao hàng trễ.", difficulty: "MEDIUM" },
      { word: "delegate", ipa: "ˈdɛlɪɡeɪt", partOfSpeech: "verb", meaningVi: "ủy quyền, giao việc", definitionEn: "To give a task or responsibility to another person.", exampleEn: "A good manager knows how to delegate tasks effectively.", exampleVi: "Một quản lý giỏi biết cách giao việc hiệu quả.", difficulty: "MEDIUM" },
      { word: "forecast", ipa: "ˈfɔːrkæst", partOfSpeech: "noun", meaningVi: "dự báo", definitionEn: "A prediction of future events or trends based on data.", exampleEn: "The sales forecast for next quarter looks promising.", exampleVi: "Dự báo doanh số cho quý tới trông rất khả quan.", collocations: ["sales forecast", "weather forecast"], difficulty: "MEDIUM" },
      { word: "outsource", ipa: "ˈaʊtsɔːrs", partOfSpeech: "verb", meaningVi: "thuê ngoài", definitionEn: "To pay another company to provide a service rather than employ staff to do it.", exampleEn: "The company decided to outsource its customer support to another firm.", exampleVi: "Công ty quyết định thuê ngoài dịch vụ hỗ trợ khách hàng.", difficulty: "MEDIUM" },
      { word: "compliance", ipa: "kəmˈplaɪəns", partOfSpeech: "noun", meaningVi: "sự tuân thủ", definitionEn: "The act of obeying a rule, law, or standard.", exampleEn: "All branches must be in compliance with the new safety code.", exampleVi: "Mọi chi nhánh phải tuân thủ quy định an toàn mới.", difficulty: "MEDIUM" },
      { word: "diversify", ipa: "daɪˈvɜːrsɪfaɪ", partOfSpeech: "verb", meaningVi: "đa dạng hóa", definitionEn: "To vary or expand a range of products or investments.", exampleEn: "The firm is diversifying its product line to reach new markets.", exampleVi: "Công ty đang đa dạng hóa dòng sản phẩm để tiếp cận thị trường mới.", difficulty: "MEDIUM" },
      { word: "feasible", ipa: "ˈfiːzəbəl", partOfSpeech: "adjective", meaningVi: "khả thi", definitionEn: "Possible to do easily or conveniently.", exampleEn: "It is not feasible to finish the project by Friday.", exampleVi: "Không khả thi để hoàn thành dự án trước thứ Sáu.", synonyms: ["viable", "practical"], difficulty: "MEDIUM" },
      { word: "downturn", ipa: "ˈdaʊntɜːrn", partOfSpeech: "noun", meaningVi: "sự suy thoái", definitionEn: "A decline in economic or business activity.", exampleEn: "The company cut costs during the recent economic downturn.", exampleVi: "Công ty đã cắt giảm chi phí trong đợt suy thoái kinh tế gần đây.", difficulty: "MEDIUM" },
      { word: "incentive", ipa: "ɪnˈsɛntɪv", partOfSpeech: "noun", meaningVi: "động lực, ưu đãi khuyến khích", definitionEn: "Something that encourages a person to do something.", exampleEn: "The firm offers financial incentives for employees who exceed their targets.", exampleVi: "Công ty cung cấp ưu đãi tài chính cho nhân viên vượt chỉ tiêu.", collocations: ["financial incentive", "incentive program"], difficulty: "MEDIUM" },
      { word: "collaborate", ipa: "kəˈlæbəreɪt", partOfSpeech: "verb", meaningVi: "hợp tác", definitionEn: "To work jointly with others on an activity or project.", exampleEn: "The design and engineering teams collaborated on the new prototype.", exampleVi: "Nhóm thiết kế và kỹ thuật đã hợp tác trong nguyên mẫu mới.", difficulty: "MEDIUM" },
      { word: "productivity", ipa: "ˌproʊdʌkˈtɪvɪti", partOfSpeech: "noun", meaningVi: "năng suất", definitionEn: "The rate at which goods are produced or work is completed.", exampleEn: "Flexible working hours have improved overall productivity.", exampleVi: "Giờ làm việc linh hoạt đã cải thiện năng suất chung.", difficulty: "MEDIUM" },
    ],
  },
  {
    slug: "band-800",
    name: "TOEIC 800+",
    description: "Từ vựng nâng cao, đa nghĩa và collocation thường gặp cho mốc 800 điểm.",
    category: "Theo band điểm",
    words: [
      { word: "leverage", ipa: "ˈlɛvərɪdʒ", partOfSpeech: "verb", meaningVi: "tận dụng, khai thác", definitionEn: "To use something to maximum advantage.", exampleEn: "The startup leveraged social media to reach a wider audience.", exampleVi: "Công ty khởi nghiệp đã tận dụng mạng xã hội để tiếp cận nhiều khách hàng hơn.", difficulty: "HARD" },
      { word: "contingency", ipa: "kənˈtɪndʒənsi", partOfSpeech: "noun", meaningVi: "tình huống bất ngờ, dự phòng", definitionEn: "A possible future event that must be prepared for.", exampleEn: "The firm keeps a contingency fund in case of unexpected costs.", exampleVi: "Công ty duy trì một quỹ dự phòng phòng khi có chi phí phát sinh.", collocations: ["contingency plan", "contingency fund"], difficulty: "HARD" },
      { word: "discrepancy", ipa: "dɪˈskrɛpənsi", partOfSpeech: "noun", meaningVi: "sự chênh lệch, không nhất quán", definitionEn: "A difference between two things that should be the same.", exampleEn: "Accountants found a discrepancy between the invoice and the payment record.", exampleVi: "Kế toán phát hiện sự chênh lệch giữa hóa đơn và hồ sơ thanh toán.", difficulty: "HARD" },
      { word: "stringent", ipa: "ˈstrɪndʒənt", partOfSpeech: "adjective", meaningVi: "nghiêm ngặt", definitionEn: "Strict and demanding to a very high standard.", exampleEn: "The factory must meet stringent quality standards before export.", exampleVi: "Nhà máy phải đáp ứng tiêu chuẩn chất lượng nghiêm ngặt trước khi xuất khẩu.", synonyms: ["strict", "rigorous"], difficulty: "HARD" },
      { word: "underlying", ipa: "ˌʌndərˈlaɪɪŋ", partOfSpeech: "adjective", meaningVi: "tiềm ẩn, cơ bản", definitionEn: "Being the real or basic cause or nature of something, though not immediately obvious.", exampleEn: "The consultant identified the underlying cause of the delivery delays.", exampleVi: "Chuyên gia tư vấn đã xác định nguyên nhân tiềm ẩn của việc giao hàng chậm.", collocations: ["underlying cause", "underlying issue"], difficulty: "HARD" },
      { word: "warrant", ipa: "ˈwɒrənt", partOfSpeech: "verb", meaningVi: "đảm bảo, biện minh cho", definitionEn: "To justify or make a course of action necessary.", exampleEn: "The scale of the loss warrants a full investigation.", exampleVi: "Quy mô tổn thất này đảm bảo cần có một cuộc điều tra toàn diện.", difficulty: "HARD" },
      { word: "curb", ipa: "kɜːrb", partOfSpeech: "verb", meaningVi: "kiềm chế, hạn chế", definitionEn: "To restrain or keep something within limits.", exampleEn: "New measures aim to curb unnecessary spending across departments.", exampleVi: "Các biện pháp mới nhằm hạn chế chi tiêu không cần thiết giữa các phòng ban.", collocations: ["curb spending", "curb inflation"], difficulty: "HARD" },
      { word: "conducive", ipa: "kənˈduːsɪv", partOfSpeech: "adjective", meaningVi: "thuận lợi, tạo điều kiện cho", definitionEn: "Making a certain situation or outcome likely or possible.", exampleEn: "An open office layout is conducive to teamwork.", exampleVi: "Bố cục văn phòng mở tạo điều kiện thuận lợi cho làm việc nhóm.", collocations: ["conducive to"], difficulty: "HARD" },
      { word: "encompass", ipa: "ɪnˈkʌmpəs", partOfSpeech: "verb", meaningVi: "bao gồm, bao quát", definitionEn: "To include a wide range of things within its scope.", exampleEn: "The new contract encompasses maintenance as well as installation.", exampleVi: "Hợp đồng mới bao gồm cả bảo trì lẫn lắp đặt.", synonyms: ["include", "cover"], difficulty: "HARD" },
      { word: "attrition", ipa: "əˈtrɪʃən", partOfSpeech: "noun", meaningVi: "sự hao hụt (nhân sự)", definitionEn: "The gradual reduction of staff through resignation or retirement.", exampleEn: "The department reduced its headcount through natural attrition.", exampleVi: "Bộ phận đã giảm số lượng nhân sự thông qua sự hao hụt tự nhiên.", collocations: ["employee attrition", "attrition rate"], difficulty: "HARD" },
      { word: "mitigate", ipa: "ˈmɪtɪɡeɪt", partOfSpeech: "verb", meaningVi: "giảm thiểu", definitionEn: "To make something less severe or serious.", exampleEn: "The insurance policy helps mitigate financial risk in case of damage.", exampleVi: "Chính sách bảo hiểm giúp giảm thiểu rủi ro tài chính trong trường hợp thiệt hại.", collocations: ["mitigate risk"], difficulty: "HARD" },
      { word: "pending", ipa: "ˈpɛndɪŋ", partOfSpeech: "adjective", meaningVi: "đang chờ xử lý", definitionEn: "Not yet decided, dealt with, or completed.", exampleEn: "Your reimbursement is still pending approval from the finance team.", exampleVi: "Khoản hoàn trả của bạn vẫn đang chờ phòng tài chính phê duyệt.", collocations: ["pending approval", "pending review"], difficulty: "MEDIUM" },
      { word: "discretion", ipa: "dɪˈskrɛʃən", partOfSpeech: "noun", meaningVi: "quyền tự quyết, sự thận trọng", definitionEn: "The freedom to decide what should be done in a particular situation.", exampleEn: "Refunds beyond the policy period are granted at the manager's discretion.", exampleVi: "Việc hoàn tiền ngoài thời hạn chính sách do quản lý tự quyết định.", collocations: ["at one's discretion"], difficulty: "HARD" },
      { word: "obsolete", ipa: "ˌɒbsəˈliːt", partOfSpeech: "adjective", meaningVi: "lỗi thời", definitionEn: "No longer produced or used; out of date.", exampleEn: "The old billing system has become obsolete since the upgrade.", exampleVi: "Hệ thống thanh toán cũ đã trở nên lỗi thời kể từ khi nâng cấp.", difficulty: "HARD" },
      { word: "resilient", ipa: "rɪˈzɪliənt", partOfSpeech: "adjective", meaningVi: "kiên cường, có khả năng phục hồi", definitionEn: "Able to recover quickly from difficult conditions.", exampleEn: "The company proved resilient despite the tough market conditions.", exampleVi: "Công ty đã chứng tỏ khả năng phục hồi dù điều kiện thị trường khó khăn.", difficulty: "HARD" },
      { word: "subsidiary", ipa: "səbˈsɪdiˌɛri", partOfSpeech: "noun", meaningVi: "công ty con", definitionEn: "A company that is owned or controlled by another, larger company.", exampleEn: "The parent company opened a new subsidiary in Vietnam.", exampleVi: "Công ty mẹ đã mở một công ty con mới tại Việt Nam.", difficulty: "HARD" },
      { word: "defer", ipa: "dɪˈfɜːr", partOfSpeech: "verb", meaningVi: "hoãn lại, trì hoãn", definitionEn: "To put off an action or event to a later time.", exampleEn: "The board decided to defer the decision until next quarter.", exampleVi: "Hội đồng quản trị quyết định hoãn quyết định đến quý sau.", synonyms: ["postpone"], difficulty: "HARD" },
      { word: "grievance", ipa: "ˈɡriːvəns", partOfSpeech: "noun", meaningVi: "khiếu nại (chính thức)", definitionEn: "A formal complaint made by an employee about unfair treatment.", exampleEn: "The employee filed a grievance with the human resources department.", exampleVi: "Nhân viên đã nộp đơn khiếu nại lên phòng nhân sự.", collocations: ["file a grievance"], difficulty: "HARD" },
    ],
  },
  {
    slug: "band-900-plus",
    name: "TOEIC 900+",
    description: "Từ vựng học thuật, trang trọng và idiomatic cho mốc 900+ điểm.",
    category: "Theo band điểm",
    words: [
      { word: "expedite", ipa: "ˈɛkspɪdaɪt", partOfSpeech: "verb", meaningVi: "đẩy nhanh, xúc tiến", definitionEn: "To make a process happen more quickly.", exampleEn: "The supplier agreed to expedite the shipment at no extra cost.", exampleVi: "Nhà cung cấp đồng ý đẩy nhanh việc giao hàng mà không tính thêm phí.", difficulty: "HARD" },
      { word: "circumvent", ipa: "ˌsɜːrkəmˈvɛnt", partOfSpeech: "verb", meaningVi: "lách, tránh né (quy định)", definitionEn: "To find a way around an obstacle or rule, often cleverly.", exampleEn: "The proposal was designed to circumvent lengthy approval procedures.", exampleVi: "Đề xuất được thiết kế nhằm lách qua các thủ tục phê duyệt rườm rà.", difficulty: "HARD" },
      { word: "tenure", ipa: "ˈtɛnjər", partOfSpeech: "noun", meaningVi: "nhiệm kỳ, thời gian đảm nhiệm", definitionEn: "The period during which a person holds a position or office.", exampleEn: "Revenue doubled during her tenure as chief executive.", exampleVi: "Doanh thu đã tăng gấp đôi trong nhiệm kỳ của bà với vai trò giám đốc điều hành.", difficulty: "HARD" },
      { word: "conglomerate", ipa: "kənˈɡlɒmərɪt", partOfSpeech: "noun", meaningVi: "tập đoàn (đa ngành)", definitionEn: "A large corporation formed by combining several different companies.", exampleEn: "The media conglomerate acquired two smaller publishing houses this year.", exampleVi: "Tập đoàn truyền thông đã mua lại hai nhà xuất bản nhỏ hơn trong năm nay.", difficulty: "HARD" },
      { word: "unprecedented", ipa: "ʌnˈprɛsɪˌdɛntɪd", partOfSpeech: "adjective", meaningVi: "chưa từng có tiền lệ", definitionEn: "Never having happened or existed before.", exampleEn: "The firm reported unprecedented growth in overseas markets last year.", exampleVi: "Công ty báo cáo mức tăng trưởng chưa từng có ở thị trường nước ngoài năm ngoái.", difficulty: "HARD" },
      { word: "expedient", ipa: "ɪkˈspiːdiənt", partOfSpeech: "adjective", meaningVi: "thuận tiện (nhưng có thể thiếu nguyên tắc)", definitionEn: "Convenient and practical, though sometimes not the most ethical option.", exampleEn: "Cutting corners on inspections may seem expedient but risks safety.", exampleVi: "Việc cắt giảm khâu kiểm tra có vẻ thuận tiện nhưng lại gây rủi ro an toàn.", difficulty: "HARD" },
      { word: "consolidate", ipa: "kənˈsɒlɪdeɪt", partOfSpeech: "verb", meaningVi: "hợp nhất, củng cố", definitionEn: "To combine several things into a single, more effective whole.", exampleEn: "The two departments were consolidated to reduce overhead costs.", exampleVi: "Hai phòng ban đã được hợp nhất để giảm chi phí vận hành.", difficulty: "HARD" },
      { word: "spearhead", ipa: "ˈspɪərhɛd", partOfSpeech: "verb", meaningVi: "dẫn đầu, đi tiên phong", definitionEn: "To lead an activity or organization to make sure it succeeds.", exampleEn: "She was chosen to spearhead the company's expansion into Asia.", exampleVi: "Bà được chọn để dẫn đầu quá trình mở rộng của công ty sang châu Á.", difficulty: "HARD" },
      { word: "insolvent", ipa: "ɪnˈsɒlvənt", partOfSpeech: "adjective", meaningVi: "mất khả năng thanh toán", definitionEn: "Unable to pay debts owed.", exampleEn: "The retailer was declared insolvent after years of declining sales.", exampleVi: "Nhà bán lẻ được tuyên bố mất khả năng thanh toán sau nhiều năm doanh số sụt giảm.", difficulty: "HARD" },
      { word: "corroborate", ipa: "kəˈrɒbəreɪt", partOfSpeech: "verb", meaningVi: "xác thực, củng cố (bằng chứng)", definitionEn: "To confirm or give support to a statement or finding.", exampleEn: "The audit findings corroborate the earlier report on lost inventory.", exampleVi: "Kết quả kiểm toán xác thực cho báo cáo trước đó về hàng tồn kho thất thoát.", difficulty: "HARD" },
      { word: "exorbitant", ipa: "ɪɡˈzɔːrbɪtənt", partOfSpeech: "adjective", meaningVi: "cắt cổ, quá đắt", definitionEn: "Unreasonably high, especially of a price or charge.", exampleEn: "Shareholders criticized the exorbitant bonuses paid to senior executives.", exampleVi: "Các cổ đông chỉ trích khoản thưởng quá cao trả cho lãnh đạo cấp cao.", difficulty: "HARD" },
      { word: "encroach", ipa: "ɪnˈkroʊtʃ", partOfSpeech: "verb", meaningVi: "lấn chiếm, xâm phạm dần", definitionEn: "To gradually intrude on a territory, rights, or area of activity.", exampleEn: "Online retailers continue to encroach on the market share of traditional stores.", exampleVi: "Các nhà bán lẻ trực tuyến tiếp tục lấn chiếm thị phần của các cửa hàng truyền thống.", collocations: ["encroach on"], difficulty: "HARD" },
      { word: "at the eleventh hour", ipa: "æt ðə ɪˈlɛvənθ ˈaʊər", partOfSpeech: "phrase", meaningVi: "vào phút chót", definitionEn: "At the last possible moment, just before it would be too late.", exampleEn: "The deal was finally signed at the eleventh hour, minutes before the deadline.", exampleVi: "Thỏa thuận cuối cùng đã được ký vào phút chót, ngay trước hạn chót.", difficulty: "HARD" },
      { word: "across the board", ipa: "əˈkrɒs ðə bɔːrd", partOfSpeech: "phrase", meaningVi: "trên diện rộng, áp dụng đồng loạt", definitionEn: "Applying to all people, groups, or things without exception.", exampleEn: "The company announced a 5 percent pay increase across the board.", exampleVi: "Công ty thông báo tăng lương 5% cho toàn bộ nhân viên.", difficulty: "HARD" },
      { word: "cut corners", ipa: "kʌt ˈkɔːrnərz", partOfSpeech: "phrasal verb", meaningVi: "làm ẩu, cắt giảm để tiết kiệm", definitionEn: "To do something in the easiest or cheapest way, often sacrificing quality.", exampleEn: "The contractor cut corners on materials, and the roof failed within a year.", exampleVi: "Nhà thầu đã làm ẩu về vật liệu, và mái nhà hỏng chỉ sau một năm.", difficulty: "HARD" },
      { word: "iron out", ipa: "ˈaɪərn aʊt", partOfSpeech: "phrasal verb", meaningVi: "giải quyết ổn thỏa (vấn đề nhỏ)", definitionEn: "To resolve difficulties or differences through discussion.", exampleEn: "The two sides met to iron out the remaining details of the contract.", exampleVi: "Hai bên đã gặp nhau để giải quyết ổn thỏa những chi tiết còn lại của hợp đồng.", difficulty: "HARD" },
      { word: "shell out", ipa: "ʃɛl aʊt", partOfSpeech: "phrasal verb", meaningVi: "chi (tiền), móc hầu bao", definitionEn: "To pay, often reluctantly, a large amount of money for something.", exampleEn: "The firm had to shell out a fortune to settle the lawsuit.", exampleVi: "Công ty đã phải chi một khoản tiền lớn để giải quyết vụ kiện.", difficulty: "HARD" },
      { word: "keep abreast of", ipa: "kiːp əˈbrɛst ʌv", partOfSpeech: "phrase", meaningVi: "cập nhật, theo kịp (thông tin)", definitionEn: "To stay informed about the latest developments in a subject.", exampleEn: "Managers must keep abreast of changes in trade regulations.", exampleVi: "Các quản lý phải cập nhật những thay đổi trong quy định thương mại.", difficulty: "HARD" },
    ],
  },
];
