export interface SeedWord {
  word: string;
  ipa: string;
  partOfSpeech: string;
  meaningVi: string;
  definitionEn: string;
  exampleEn: string;
  exampleVi: string;
  synonyms?: string[];
  collocations?: string[];
  difficulty?: "EASY" | "MEDIUM" | "HARD";
}

export interface SeedVocabularyTopic {
  slug: string;
  name: string;
  description: string;
  category: string;
  words: SeedWord[];
}

export const VOCABULARY_TOPICS_PHRASES: SeedVocabularyTopic[] = [
  {
    slug: "phrasal-verbs",
    name: "Cụm động từ (Phrasal Verbs)",
    description: "Các cụm động từ thông dụng và thường bị nhầm nghĩa trong TOEIC.",
    category: "Cụm từ cố định & thường gặp",
    words: [
      { word: "carry out", ipa: "ˈkæri aʊt", partOfSpeech: "phrasal verb", meaningVi: "thực hiện, tiến hành", definitionEn: "To perform or complete a task, plan, or instruction.", exampleEn: "The maintenance crew will carry out repairs on the elevator this weekend.", exampleVi: "Đội bảo trì sẽ tiến hành sửa chữa thang máy vào cuối tuần này.", synonyms: ["perform", "execute"], collocations: ["carry out an inspection", "carry out a survey"] },
      { word: "come up with", ipa: "kʌm ʌp wɪð", partOfSpeech: "phrasal verb", meaningVi: "nghĩ ra, đưa ra", definitionEn: "To produce or think of an idea or plan.", exampleEn: "The design team came up with a new logo for the product launch.", exampleVi: "Nhóm thiết kế đã nghĩ ra một logo mới cho đợt ra mắt sản phẩm.", synonyms: ["devise", "propose"], difficulty: "MEDIUM" },
      { word: "put off", ipa: "pʊt ɔːf", partOfSpeech: "phrasal verb", meaningVi: "hoãn lại, trì hoãn", definitionEn: "To postpone an event or action to a later time.", exampleEn: "Management decided to put off the product launch until next quarter.", exampleVi: "Ban quản lý đã quyết định hoãn việc ra mắt sản phẩm đến quý sau.", synonyms: ["postpone", "delay"] },
      { word: "fill out", ipa: "fɪl aʊt", partOfSpeech: "phrasal verb", meaningVi: "điền vào (mẫu đơn)", definitionEn: "To complete a form by writing the required information.", exampleEn: "New employees must fill out several forms before their first day.", exampleVi: "Nhân viên mới phải điền vào một số mẫu đơn trước ngày làm việc đầu tiên.", synonyms: ["complete"], collocations: ["fill out an application"] },
      { word: "hand in", ipa: "hænd ɪn", partOfSpeech: "phrasal verb", meaningVi: "nộp (báo cáo, tài liệu)", definitionEn: "To submit a document or piece of work to someone.", exampleEn: "Please hand in your expense report by the end of the week.", exampleVi: "Vui lòng nộp báo cáo chi phí trước cuối tuần.", synonyms: ["submit"] },
      { word: "set up", ipa: "sɛt ʌp", partOfSpeech: "phrasal verb", meaningVi: "thiết lập, thành lập", definitionEn: "To establish or arrange something so it is ready for use.", exampleEn: "The IT department will set up new computers for the marketing team.", exampleVi: "Phòng IT sẽ thiết lập máy tính mới cho nhóm marketing.", synonyms: ["establish", "arrange"], collocations: ["set up a meeting", "set up an account"] },
      { word: "look into", ipa: "lʊk ˈɪntuː", partOfSpeech: "phrasal verb", meaningVi: "điều tra, xem xét", definitionEn: "To investigate or examine a matter closely.", exampleEn: "The manager promised to look into the customer's complaint immediately.", exampleVi: "Người quản lý hứa sẽ điều tra khiếu nại của khách hàng ngay lập tức.", synonyms: ["investigate", "examine"], difficulty: "MEDIUM" },
      { word: "cut back on", ipa: "kʌt bæk ɒn", partOfSpeech: "phrasal verb", meaningVi: "cắt giảm", definitionEn: "To reduce the amount of something, especially spending.", exampleEn: "The firm had to cut back on travel expenses during the downturn.", exampleVi: "Công ty phải cắt giảm chi phí đi lại trong thời kỳ suy thoái.", synonyms: ["reduce", "curtail"], difficulty: "HARD" },
      { word: "take over", ipa: "teɪk ˈoʊvər", partOfSpeech: "phrasal verb", meaningVi: "tiếp quản", definitionEn: "To assume control of or responsibility for something.", exampleEn: "Ms. Tran will take over the regional office once Mr. Kim retires.", exampleVi: "Bà Trần sẽ tiếp quản văn phòng khu vực khi ông Kim nghỉ hưu.", synonyms: ["assume control of"], collocations: ["takeover bid"] },
      { word: "go over", ipa: "ɡoʊ ˈoʊvər", partOfSpeech: "phrasal verb", meaningVi: "xem xét lại, rà soát", definitionEn: "To review or examine something in detail.", exampleEn: "Let's go over the budget figures before the presentation.", exampleVi: "Hãy cùng rà soát lại các con số ngân sách trước buổi thuyết trình.", synonyms: ["review", "examine"] },
      { word: "sign up for", ipa: "saɪn ʌp fɔːr", partOfSpeech: "phrasal verb", meaningVi: "đăng ký (tham gia)", definitionEn: "To register or enroll for an activity or service.", exampleEn: "Staff members can sign up for the training workshop online.", exampleVi: "Nhân viên có thể đăng ký tham gia buổi hội thảo đào tạo trực tuyến.", synonyms: ["enroll in", "register for"] },
      { word: "hold off on", ipa: "hoʊld ɔːf ɒn", partOfSpeech: "phrasal verb", meaningVi: "trì hoãn, tạm ngừng", definitionEn: "To delay doing something until a later, more suitable time.", exampleEn: "We will hold off on hiring until the new budget is approved.", exampleVi: "Chúng tôi sẽ tạm ngừng tuyển dụng cho đến khi ngân sách mới được phê duyệt.", synonyms: ["postpone", "defer"], difficulty: "HARD" },
      { word: "roll out", ipa: "roʊl aʊt", partOfSpeech: "phrasal verb", meaningVi: "triển khai, tung ra", definitionEn: "To launch or introduce a new product, service, or policy widely.", exampleEn: "The company plans to roll out the updated software next month.", exampleVi: "Công ty dự định triển khai phần mềm cập nhật vào tháng tới.", synonyms: ["launch", "introduce"], difficulty: "MEDIUM" },
      { word: "phase out", ipa: "feɪz aʊt", partOfSpeech: "phrasal verb", meaningVi: "loại bỏ dần", definitionEn: "To gradually stop using or producing something.", exampleEn: "The manufacturer will phase out the older model by the end of the year.", exampleVi: "Nhà sản xuất sẽ loại bỏ dần mẫu cũ vào cuối năm.", synonyms: ["discontinue gradually"], difficulty: "HARD" },
      { word: "back up", ipa: "bæk ʌp", partOfSpeech: "phrasal verb", meaningVi: "sao lưu; hỗ trợ", definitionEn: "To make a copy of data for safekeeping, or to support someone.", exampleEn: "Employees are required to back up their files every evening.", exampleVi: "Nhân viên được yêu cầu sao lưu tệp của mình mỗi tối.", synonyms: ["duplicate", "support"] },
      { word: "draw up", ipa: "drɔː ʌp", partOfSpeech: "phrasal verb", meaningVi: "soạn thảo", definitionEn: "To prepare a formal document such as a contract or plan.", exampleEn: "The legal team will draw up a new contract for the supplier.", exampleVi: "Đội ngũ pháp lý sẽ soạn thảo một hợp đồng mới cho nhà cung cấp.", synonyms: ["draft", "prepare"], difficulty: "MEDIUM" },
    ],
  },
  {
    slug: "verb-preposition",
    name: "Động từ đi kèm giới từ cố định",
    description: "Các động từ luôn đi cùng một giới từ cố định, hay xuất hiện trong Part 5-6.",
    category: "Cụm từ cố định & thường gặp",
    words: [
      { word: "comply with", ipa: "kəmˈplaɪ wɪð", partOfSpeech: "verb + preposition", meaningVi: "tuân thủ", definitionEn: "To act in accordance with a rule, request, or regulation.", exampleEn: "All contractors must comply with the new safety regulations.", exampleVi: "Tất cả nhà thầu phải tuân thủ các quy định an toàn mới.", synonyms: ["adhere to", "conform to"], collocations: ["comply with a policy"] },
      { word: "consist of", ipa: "kənˈsɪst ʌv", partOfSpeech: "verb + preposition", meaningVi: "bao gồm, gồm có", definitionEn: "To be made up of particular parts or elements.", exampleEn: "The committee consists of five members from different departments.", exampleVi: "Ủy ban bao gồm năm thành viên từ các phòng ban khác nhau.", synonyms: ["comprise", "be composed of"] },
      { word: "refer to", ipa: "rɪˈfɜːr tuː", partOfSpeech: "verb + preposition", meaningVi: "tham khảo, đề cập đến", definitionEn: "To direct attention to something or mention it.", exampleEn: "Please refer to the attached manual for installation instructions.", exampleVi: "Vui lòng tham khảo hướng dẫn sử dụng đính kèm để biết cách lắp đặt.", synonyms: ["consult", "mention"] },
      { word: "account for", ipa: "əˈkaʊnt fɔːr", partOfSpeech: "verb + preposition", meaningVi: "chiếm (tỷ lệ), giải thích cho", definitionEn: "To form a certain amount or proportion, or to explain the cause of something.", exampleEn: "Overseas sales account for nearly 40 percent of total revenue.", exampleVi: "Doanh số bán hàng nước ngoài chiếm gần 40% tổng doanh thu.", synonyms: ["constitute", "explain"], difficulty: "HARD" },
      { word: "apply for", ipa: "əˈplaɪ fɔːr", partOfSpeech: "verb + preposition", meaningVi: "nộp đơn xin", definitionEn: "To formally request something, such as a job or permit.", exampleEn: "Candidates should apply for the position by submitting an online form.", exampleVi: "Ứng viên nên nộp đơn xin vị trí này bằng cách gửi biểu mẫu trực tuyến.", collocations: ["apply for a loan", "apply for a visa"] },
      { word: "benefit from", ipa: "ˈbɛnɪfɪt frʌm", partOfSpeech: "verb + preposition", meaningVi: "hưởng lợi từ", definitionEn: "To gain an advantage from something.", exampleEn: "Small businesses can benefit from the government's new tax incentives.", exampleVi: "Các doanh nghiệp nhỏ có thể hưởng lợi từ các ưu đãi thuế mới của chính phủ.", synonyms: ["gain from", "profit from"] },
      { word: "collaborate with", ipa: "kəˈlæbəreɪt wɪð", partOfSpeech: "verb + preposition", meaningVi: "hợp tác với", definitionEn: "To work jointly with someone on a project or activity.", exampleEn: "Our research team collaborates with several universities abroad.", exampleVi: "Nhóm nghiên cứu của chúng tôi hợp tác với một số trường đại học ở nước ngoài.", synonyms: ["cooperate with", "team up with"], difficulty: "MEDIUM" },
      { word: "compensate for", ipa: "ˈkɒmpənseɪt fɔːr", partOfSpeech: "verb + preposition", meaningVi: "bù đắp cho", definitionEn: "To make up for a loss, damage, or shortfall.", exampleEn: "The airline offered vouchers to compensate for the flight delay.", exampleVi: "Hãng hàng không đã tặng phiếu mua hàng để bù đắp cho việc chuyến bay bị trễ.", synonyms: ["make up for"], difficulty: "HARD" },
      { word: "contribute to", ipa: "kənˈtrɪbjuːt tuː", partOfSpeech: "verb + preposition", meaningVi: "đóng góp vào", definitionEn: "To help cause or bring about a result, or to give something as a share.", exampleEn: "Every employee's effort contributes to the company's overall success.", exampleVi: "Nỗ lực của mỗi nhân viên đều đóng góp vào thành công chung của công ty.", synonyms: ["add to"] },
      { word: "deal with", ipa: "diːl wɪð", partOfSpeech: "verb + preposition", meaningVi: "xử lý, giải quyết", definitionEn: "To take action to handle a problem, task, or person.", exampleEn: "The customer service team deals with complaints on a daily basis.", exampleVi: "Đội ngũ chăm sóc khách hàng xử lý khiếu nại hàng ngày.", synonyms: ["handle", "manage"] },
      { word: "invest in", ipa: "ɪnˈvɛst ɪn", partOfSpeech: "verb + preposition", meaningVi: "đầu tư vào", definitionEn: "To put money, time, or effort into something expecting a future benefit.", exampleEn: "The corporation plans to invest in renewable energy projects.", exampleVi: "Tập đoàn có kế hoạch đầu tư vào các dự án năng lượng tái tạo.", collocations: ["invest in technology"] },
      { word: "participate in", ipa: "pɑːrˈtɪsɪpeɪt ɪn", partOfSpeech: "verb + preposition", meaningVi: "tham gia vào", definitionEn: "To take part in an activity or event.", exampleEn: "All department heads are expected to participate in the annual review.", exampleVi: "Tất cả trưởng phòng đều được yêu cầu tham gia buổi đánh giá thường niên.", synonyms: ["take part in"] },
      { word: "qualify for", ipa: "ˈkwɒlɪfaɪ fɔːr", partOfSpeech: "verb + preposition", meaningVi: "đủ điều kiện cho", definitionEn: "To have the necessary skills or qualifications to be entitled to something.", exampleEn: "Employees with two years of service qualify for extra vacation days.", exampleVi: "Nhân viên có hai năm thâm niên đủ điều kiện được thêm ngày nghỉ phép.", synonyms: ["be eligible for"], difficulty: "MEDIUM" },
      { word: "specialize in", ipa: "ˈspɛʃəlaɪz ɪn", partOfSpeech: "verb + preposition", meaningVi: "chuyên về", definitionEn: "To focus one's business or skills on a particular area.", exampleEn: "This law firm specializes in intellectual property disputes.", exampleVi: "Công ty luật này chuyên về các tranh chấp sở hữu trí tuệ.", synonyms: ["focus on"] },
      { word: "consult with", ipa: "kənˈsʌlt wɪð", partOfSpeech: "verb + preposition", meaningVi: "tham vấn, hỏi ý kiến", definitionEn: "To seek advice or information from someone before making a decision.", exampleEn: "Please consult with the legal department before signing the agreement.", exampleVi: "Vui lòng tham vấn phòng pháp lý trước khi ký thỏa thuận.", synonyms: ["seek advice from"], difficulty: "HARD" },
      { word: "cope with", ipa: "koʊp wɪð", partOfSpeech: "verb + preposition", meaningVi: "đối phó với", definitionEn: "To deal successfully with a difficult situation.", exampleEn: "The support team struggled to cope with the sudden surge in orders.", exampleVi: "Đội ngũ hỗ trợ đã gặp khó khăn khi đối phó với sự gia tăng đột ngột về đơn hàng.", synonyms: ["manage", "handle"], difficulty: "MEDIUM" },
    ],
  },
  {
    slug: "adjective-preposition",
    name: "Tính từ đi kèm giới từ cố định",
    description: "Các tính từ luôn đi cùng một giới từ cố định, hay xuất hiện trong Part 5-6.",
    category: "Cụm từ cố định & thường gặp",
    words: [
      { word: "responsible for", ipa: "rɪˈspɒnsəbəl fɔːr", partOfSpeech: "adjective + preposition", meaningVi: "chịu trách nhiệm về", definitionEn: "Having control over or being accountable for something.", exampleEn: "Mr. Park is responsible for coordinating the annual conference.", exampleVi: "Ông Park chịu trách nhiệm điều phối hội nghị thường niên." },
      { word: "eligible for", ipa: "ˈɛlɪdʒəbəl fɔːr", partOfSpeech: "adjective + preposition", meaningVi: "đủ điều kiện để", definitionEn: "Having the right to be considered for or to receive something.", exampleEn: "Full-time staff are eligible for health insurance benefits.", exampleVi: "Nhân viên toàn thời gian đủ điều kiện nhận phúc lợi bảo hiểm y tế.", synonyms: ["qualified for"], difficulty: "MEDIUM" },
      { word: "familiar with", ipa: "fəˈmɪliər wɪð", partOfSpeech: "adjective + preposition", meaningVi: "quen thuộc với", definitionEn: "Having good knowledge or experience of something.", exampleEn: "New hires should become familiar with the company's code of conduct.", exampleVi: "Nhân viên mới nên làm quen với quy tắc ứng xử của công ty." },
      { word: "committed to", ipa: "kəˈmɪtɪd tuː", partOfSpeech: "adjective + preposition", meaningVi: "cam kết với", definitionEn: "Dedicated to a cause, activity, or course of action.", exampleEn: "The company is committed to reducing its environmental impact.", exampleVi: "Công ty cam kết giảm thiểu tác động đến môi trường.", synonyms: ["dedicated to"] },
      { word: "aware of", ipa: "əˈwɛr ʌv", partOfSpeech: "adjective + preposition", meaningVi: "nhận thức được, biết về", definitionEn: "Having knowledge or perception of a situation or fact.", exampleEn: "Employees should be aware of the updated expense policy.", exampleVi: "Nhân viên nên nhận thức được chính sách chi phí đã được cập nhật." },
      { word: "capable of", ipa: "ˈkeɪpəbəl ʌv", partOfSpeech: "adjective + preposition", meaningVi: "có khả năng", definitionEn: "Having the ability or capacity to do something.", exampleEn: "The new printer is capable of producing 60 pages per minute.", exampleVi: "Máy in mới có khả năng in được 60 trang mỗi phút." },
      { word: "consistent with", ipa: "kənˈsɪstənt wɪð", partOfSpeech: "adjective + preposition", meaningVi: "phù hợp, nhất quán với", definitionEn: "In agreement with or not contradicting something.", exampleEn: "The proposed budget is consistent with last year's spending plan.", exampleVi: "Ngân sách đề xuất phù hợp với kế hoạch chi tiêu của năm ngoái.", difficulty: "HARD" },
      { word: "dependent on", ipa: "dɪˈpɛndənt ɒn", partOfSpeech: "adjective + preposition", meaningVi: "phụ thuộc vào", definitionEn: "Relying on something else for support or existence.", exampleEn: "The project's timeline is dependent on the supplier's delivery schedule.", exampleVi: "Tiến độ dự án phụ thuộc vào lịch giao hàng của nhà cung cấp.", synonyms: ["reliant on"], difficulty: "MEDIUM" },
      { word: "equivalent to", ipa: "ɪˈkwɪvələnt tuː", partOfSpeech: "adjective + preposition", meaningVi: "tương đương với", definitionEn: "Equal in value, amount, or meaning to something else.", exampleEn: "One year of relevant experience is equivalent to a training certificate.", exampleVi: "Một năm kinh nghiệm liên quan tương đương với một chứng chỉ đào tạo.", difficulty: "HARD" },
      { word: "exempt from", ipa: "ɪɡˈzɛmpt frʌm", partOfSpeech: "adjective + preposition", meaningVi: "được miễn khỏi", definitionEn: "Free from an obligation or liability that applies to others.", exampleEn: "Nonprofit organizations are exempt from this local tax.", exampleVi: "Các tổ chức phi lợi nhuận được miễn loại thuế địa phương này.", difficulty: "HARD" },
      { word: "grateful for", ipa: "ˈɡreɪtfəl fɔːr", partOfSpeech: "adjective + preposition", meaningVi: "biết ơn về", definitionEn: "Feeling or showing thanks for something.", exampleEn: "We are grateful for your continued support over the years.", exampleVi: "Chúng tôi biết ơn sự hỗ trợ liên tục của quý vị trong suốt những năm qua." },
      { word: "involved in", ipa: "ɪnˈvɒlvd ɪn", partOfSpeech: "adjective + preposition", meaningVi: "tham gia vào, liên quan đến", definitionEn: "Taking part in or connected with an activity or situation.", exampleEn: "Three departments were involved in developing the new policy.", exampleVi: "Ba phòng ban đã tham gia vào việc xây dựng chính sách mới." },
      { word: "proficient in", ipa: "prəˈfɪʃənt ɪn", partOfSpeech: "adjective + preposition", meaningVi: "thành thạo trong", definitionEn: "Highly skilled or competent in a particular area.", exampleEn: "Applicants must be proficient in at least two spreadsheet programs.", exampleVi: "Ứng viên phải thành thạo ít nhất hai chương trình bảng tính.", synonyms: ["skilled in"], difficulty: "MEDIUM" },
      { word: "reluctant to", ipa: "rɪˈlʌktənt tuː", partOfSpeech: "adjective + preposition", meaningVi: "miễn cưỡng, do dự", definitionEn: "Unwilling to do something and hesitant about it.", exampleEn: "Investors were reluctant to commit funds during the uncertain market.", exampleVi: "Các nhà đầu tư miễn cưỡng cam kết vốn trong thời kỳ thị trường bất ổn.", synonyms: ["hesitant to"], difficulty: "HARD" },
      { word: "subject to", ipa: "ˈsʌbdʒɪkt tuː", partOfSpeech: "adjective + preposition", meaningVi: "phụ thuộc vào, có thể bị", definitionEn: "Likely to be affected by or dependent on something, often a condition.", exampleEn: "All prices are subject to change without prior notice.", exampleVi: "Tất cả giá cả có thể thay đổi mà không cần báo trước.", difficulty: "MEDIUM" },
      { word: "compatible with", ipa: "kəmˈpætəbəl wɪð", partOfSpeech: "adjective + preposition", meaningVi: "tương thích với", definitionEn: "Able to exist, work, or be used together with something else without conflict.", exampleEn: "The new software is fully compatible with our existing database system.", exampleVi: "Phần mềm mới hoàn toàn tương thích với hệ thống cơ sở dữ liệu hiện tại của chúng tôi.", difficulty: "MEDIUM" },
    ],
  },
  {
    slug: "noun-preposition",
    name: "Danh từ đi kèm giới từ cố định",
    description: "Các danh từ luôn đi cùng một giới từ cố định, hay xuất hiện trong Part 5-6.",
    category: "Cụm từ cố định & thường gặp",
    words: [
      { word: "access to", ipa: "ˈæksɛs tuː", partOfSpeech: "noun + preposition", meaningVi: "quyền truy cập vào", definitionEn: "The right or opportunity to use or enter something.", exampleEn: "Only managers have access to the confidential sales figures.", exampleVi: "Chỉ có quản lý mới có quyền truy cập vào số liệu bán hàng bảo mật." },
      { word: "increase in", ipa: "ˈɪnkriːs ɪn", partOfSpeech: "noun + preposition", meaningVi: "sự gia tăng về", definitionEn: "A rise in the amount, level, or number of something.", exampleEn: "The report noted a sharp increase in online orders last month.", exampleVi: "Báo cáo ghi nhận sự gia tăng mạnh về đơn hàng trực tuyến trong tháng trước." },
      { word: "demand for", ipa: "dɪˈmænd fɔːr", partOfSpeech: "noun + preposition", meaningVi: "nhu cầu về", definitionEn: "A desire or requirement for a particular product or service.", exampleEn: "Demand for the new smartphone model exceeded initial projections.", exampleVi: "Nhu cầu về mẫu điện thoại thông minh mới đã vượt dự đoán ban đầu." },
      { word: "reason for", ipa: "ˈriːzən fɔːr", partOfSpeech: "noun + preposition", meaningVi: "lý do cho", definitionEn: "The cause or explanation for something happening.", exampleEn: "The main reason for the delay was a shortage of raw materials.", exampleVi: "Lý do chính cho sự chậm trễ là do thiếu nguyên liệu thô." },
      { word: "impact on", ipa: "ˈɪmpækt ɒn", partOfSpeech: "noun + preposition", meaningVi: "tác động đến", definitionEn: "A significant effect that something has on another thing.", exampleEn: "The new regulations will have a major impact on small retailers.", exampleVi: "Các quy định mới sẽ có tác động lớn đến các nhà bán lẻ nhỏ.", synonyms: ["effect on"] },
      { word: "approach to", ipa: "əˈproʊtʃ tuː", partOfSpeech: "noun + preposition", meaningVi: "cách tiếp cận đối với", definitionEn: "A way of dealing with or thinking about a particular matter.", exampleEn: "The firm adopted a more flexible approach to remote work.", exampleVi: "Công ty đã áp dụng một cách tiếp cận linh hoạt hơn đối với làm việc từ xa.", difficulty: "MEDIUM" },
      { word: "solution to", ipa: "səˈluːʃən tuː", partOfSpeech: "noun + preposition", meaningVi: "giải pháp cho", definitionEn: "A way of solving a problem or dealing with a difficult situation.", exampleEn: "The engineers proposed a practical solution to the shipping delays.", exampleVi: "Các kỹ sư đã đề xuất một giải pháp thiết thực cho vấn đề chậm trễ vận chuyển." },
      { word: "commitment to", ipa: "kəˈmɪtmənt tuː", partOfSpeech: "noun + preposition", meaningVi: "sự cam kết đối với", definitionEn: "A dedication or pledge to a cause, activity, or plan.", exampleEn: "The CEO reaffirmed the company's commitment to employee training.", exampleVi: "Giám đốc điều hành đã tái khẳng định cam kết của công ty đối với đào tạo nhân viên.", difficulty: "MEDIUM" },
      { word: "reduction in", ipa: "rɪˈdʌkʃən ɪn", partOfSpeech: "noun + preposition", meaningVi: "sự cắt giảm về", definitionEn: "A decrease in the size, amount, or degree of something.", exampleEn: "The factory reported a 15 percent reduction in production costs.", exampleVi: "Nhà máy báo cáo mức giảm 15% về chi phí sản xuất.", synonyms: ["decrease in"] },
      { word: "insight into", ipa: "ˈɪnsaɪt ˈɪntuː", partOfSpeech: "noun + preposition", meaningVi: "cái nhìn sâu sắc về", definitionEn: "A clear, deep understanding of a complicated situation.", exampleEn: "The survey offers valuable insight into customer preferences.", exampleVi: "Cuộc khảo sát mang lại cái nhìn sâu sắc có giá trị về sở thích của khách hàng.", difficulty: "HARD" },
      { word: "response to", ipa: "rɪˈspɒns tuː", partOfSpeech: "noun + preposition", meaningVi: "phản hồi đối với", definitionEn: "A reply or reaction to something that has happened or been said.", exampleEn: "In response to customer feedback, the app added a dark mode feature.", exampleVi: "Để phản hồi ý kiến của khách hàng, ứng dụng đã bổ sung tính năng chế độ tối." },
      { word: "shortage of", ipa: "ˈʃɔːrtɪdʒ ʌv", partOfSpeech: "noun + preposition", meaningVi: "sự thiếu hụt về", definitionEn: "A lack of something that is needed in sufficient amounts.", exampleEn: "A shortage of skilled workers has slowed the construction project.", exampleVi: "Sự thiếu hụt lao động lành nghề đã làm chậm tiến độ dự án xây dựng.", synonyms: ["lack of"] },
      { word: "confidence in", ipa: "ˈkɒnfɪdəns ɪn", partOfSpeech: "noun + preposition", meaningVi: "sự tin tưởng vào", definitionEn: "A feeling of trust in the ability or reliability of someone or something.", exampleEn: "Investors expressed renewed confidence in the company's leadership.", exampleVi: "Các nhà đầu tư đã bày tỏ sự tin tưởng trở lại vào ban lãnh đạo công ty.", difficulty: "MEDIUM" },
      { word: "objection to", ipa: "əbˈdʒɛkʃən tuː", partOfSpeech: "noun + preposition", meaningVi: "sự phản đối đối với", definitionEn: "A statement or feeling of disapproval or opposition toward something.", exampleEn: "Several residents raised an objection to the proposed factory site.", exampleVi: "Một số cư dân đã bày tỏ sự phản đối đối với địa điểm nhà máy được đề xuất.", difficulty: "HARD" },
      { word: "expertise in", ipa: "ˌɛkspərˈtiːz ɪn", partOfSpeech: "noun + preposition", meaningVi: "chuyên môn về", definitionEn: "Specialized knowledge or skill in a particular field.", exampleEn: "The firm hired a consultant with expertise in supply chain management.", exampleVi: "Công ty đã thuê một chuyên gia tư vấn có chuyên môn về quản lý chuỗi cung ứng.", difficulty: "HARD" },
      { word: "priority for", ipa: "praɪˈɔːrəti fɔːr", partOfSpeech: "noun + preposition", meaningVi: "ưu tiên đối với", definitionEn: "Something regarded as more important than other things for a particular group.", exampleEn: "Customer satisfaction remains a top priority for the support team.", exampleVi: "Sự hài lòng của khách hàng vẫn là ưu tiên hàng đầu đối với đội ngũ hỗ trợ.", difficulty: "MEDIUM" },
    ],
  },
];
