// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/Studio need a direct (non-pooled) connection. The app's runtime
  // PrismaClient (src/lib/db.ts) connects separately via a driver adapter and
  // uses DATABASE_URL, which may point at Supabase's pooled connection.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
