export interface SeedPart5Question {
  prompt: string;
  options: string[];
  correctIndex: number;
  explanationVi: string;
  grammarTopicSlug?: string;
  vocabularyFocus?: string[];
}

export const PART5_QUESTIONS: SeedPart5Question[] = [
  { prompt: "The marketing team will submit the revised proposal ----- Friday afternoon.", options: ["at", "by", "from", "during"], correctIndex: 1, explanationVi: "\"By + thời điểm\" diễn tả deadline (hạn chót).", grammarTopicSlug: "prepositions" },
  { prompt: "All employees ----- attend the safety training session next Monday.", options: ["must", "would", "might", "could"], correctIndex: 0, explanationVi: "'Must' diễn tả yêu cầu bắt buộc, phù hợp với ngữ cảnh quy định bắt buộc.", vocabularyFocus: ["mandatory"] },
  { prompt: "The new factory ----- twice as many units as the old one.", options: ["produce", "produces", "producing", "production"], correctIndex: 1, explanationVi: "Chủ ngữ số ít 'the new factory' cần động từ số ít chia -s: 'produces'.", grammarTopicSlug: "subject-verb-agreement" },
  { prompt: "The client was impressed by the ----- of the presentation.", options: ["professional", "professionally", "professionalism", "professionalize"], correctIndex: 2, explanationVi: "Sau 'the...of' cần danh từ: 'professionalism' (tính chuyên nghiệp).", grammarTopicSlug: "nouns" },
  { prompt: "----- the heavy rain, the outdoor event proceeded as scheduled.", options: ["Although", "Despite", "Because", "Since"], correctIndex: 1, explanationVi: "Sau chỗ trống là cụm danh từ 'the heavy rain', cần giới từ 'Despite'.", grammarTopicSlug: "conjunctions" },
  { prompt: "The board of directors ----- to approve the merger next week.", options: ["is expected", "are expected", "expecting", "expect"], correctIndex: 0, explanationVi: "'The board' là danh từ tập hợp, coi là số ít: 'is expected'.", grammarTopicSlug: "subject-verb-agreement" },
  { prompt: "Please ensure that the shipment is ----- packaged before dispatch.", options: ["secure", "securely", "security", "securing"], correctIndex: 1, explanationVi: "Cần trạng từ bổ nghĩa cho tính từ/động từ dạng bị động 'packaged': 'securely'.", grammarTopicSlug: "adverbs" },
  { prompt: "The consultant recommended ----- the current supplier contract.", options: ["review", "to review", "reviewing", "reviewed"], correctIndex: 2, explanationVi: "'Recommend' theo sau bởi gerund: 'recommended reviewing'.", grammarTopicSlug: "gerund" },
  { prompt: "Applicants must submit their resumes ----- the end of this month.", options: ["until", "by", "since", "for"], correctIndex: 1, explanationVi: "'By + thời điểm' diễn tả deadline.", grammarTopicSlug: "prepositions" },
  { prompt: "The company's profits have ----- increased over the past three years.", options: ["steady", "steadily", "steadiness", "steadier"], correctIndex: 1, explanationVi: "Cần trạng từ bổ nghĩa cho động từ 'increased': 'steadily'.", grammarTopicSlug: "adverbs" },
  { prompt: "The report ----- by the finance department was accurate and detailed.", options: ["prepare", "preparing", "prepared", "to prepare"], correctIndex: 2, explanationVi: "Phân từ quá khứ 'prepared' mang nghĩa bị động, bổ nghĩa cho 'the report'.", grammarTopicSlug: "participles" },
  { prompt: "Neither the manager nor the assistants ----- available for a meeting today.", options: ["is", "was", "are", "has been"], correctIndex: 2, explanationVi: "Cấu trúc 'neither...nor' chia động từ theo chủ ngữ gần nhất (the assistants, số nhiều): 'are'.", grammarTopicSlug: "subject-verb-agreement" },
  { prompt: "If the machine ----- properly, please contact the maintenance team immediately.", options: ["does not work", "did not work", "will not work", "not working"], correctIndex: 0, explanationVi: "Câu điều kiện loại 1: mệnh đề if dùng hiện tại đơn.", grammarTopicSlug: "conditionals" },
  { prompt: "The new employee handbook is ----- than the previous version.", options: ["comprehensive", "more comprehensive", "most comprehensive", "comprehensively"], correctIndex: 1, explanationVi: "So sánh hơn với tính từ dài: 'more comprehensive'.", grammarTopicSlug: "comparatives" },
  { prompt: "The technician ----- the printer before the client's arrival.", options: ["had fixed", "fixes", "fixing", "fix"], correctIndex: 0, explanationVi: "Hành động hoàn tất trước một mốc quá khứ khác cần quá khứ hoàn thành: 'had fixed'.", grammarTopicSlug: "verb-tense" },
  { prompt: "The workshop is designed for employees ----- want to improve their public speaking.", options: ["which", "who", "whose", "whom"], correctIndex: 1, explanationVi: "'Who' dùng cho người (employees) làm chủ ngữ của mệnh đề quan hệ.", grammarTopicSlug: "relative-clause" },
  { prompt: "The negotiation ----- successfully after three rounds of discussion.", options: ["concludes", "concluded", "conclude", "concluding"], correctIndex: 1, explanationVi: "Ngữ cảnh diễn tả một sự việc đã xảy ra trong quá khứ: 'concluded'.", grammarTopicSlug: "verb-tense" },
  { prompt: "All visitors are required to wear a ----- badge while on the premises.", options: ["visit", "visitor", "visiting", "visited"], correctIndex: 2, explanationVi: "'Visiting badge' (thẻ dành cho khách) — danh từ ghép dùng V-ing như tính từ mô tả mục đích.", vocabularyFocus: ["premises"] },
  { prompt: "The shipment will arrive ----- than expected due to the strike.", options: ["late", "later", "latest", "lately"], correctIndex: 1, explanationVi: "So sánh hơn của trạng từ 'late' là 'later'.", grammarTopicSlug: "comparatives" },
  { prompt: "----- submitting the application, candidates should double-check all required documents.", options: ["Before", "Because", "Although", "Unless"], correctIndex: 0, explanationVi: "Sau giới từ 'Before' cần V-ing: 'submitting'.", grammarTopicSlug: "gerund" },
  { prompt: "The CEO ----- a press conference to address the recent controversy.", options: ["will hold", "holding", "held to", "hold"], correctIndex: 0, explanationVi: "Ngữ cảnh diễn tả kế hoạch trong tương lai: 'will hold'.", grammarTopicSlug: "verb-tense" },
  { prompt: "Employees who arrive late ----- to notify their supervisor in advance.", options: ["ask", "asking", "are asked", "have asked"], correctIndex: 2, explanationVi: "Nhân viên 'được yêu cầu' nên cần dạng bị động: 'are asked'.", grammarTopicSlug: "passive-voice" },
  { prompt: "The customer service team handled the complaint with great ----- .", options: ["professional", "professionally", "professionalism", "professionalize"], correctIndex: 2, explanationVi: "Sau 'with great' cần danh từ trừu tượng: 'professionalism'.", grammarTopicSlug: "nouns" },
  { prompt: "This model is ----- efficient as the previous one but costs less.", options: ["as", "so", "more", "such"], correctIndex: 0, explanationVi: "So sánh bằng dùng cấu trúc 'as...as'.", grammarTopicSlug: "comparatives" },
  { prompt: "The invoice ----- attached to this email for your reference.", options: ["is", "has", "was being", "did"], correctIndex: 0, explanationVi: "Hóa đơn 'được đính kèm' nên dùng bị động hiện tại đơn: 'is attached'.", grammarTopicSlug: "passive-voice" },
  { prompt: "The vendor agreed ----- the delivery schedule to accommodate our needs.", options: ["adjust", "adjusting", "to adjust", "adjusted"], correctIndex: 2, explanationVi: "'Agree' theo sau bởi to-infinitive: 'agreed to adjust'.", grammarTopicSlug: "infinitive" },
  { prompt: "The proposal outlines several ----- to reduce operating costs.", options: ["strategy", "strategic", "strategies", "strategically"], correctIndex: 2, explanationVi: "Sau tính từ 'several' cần danh từ số nhiều: 'strategies'.", grammarTopicSlug: "nouns" },
  { prompt: "Each department head ----- required to submit a budget forecast annually.", options: ["are", "is", "were", "have been"], correctIndex: 1, explanationVi: "'Each + danh từ số ít' luôn đi với động từ số ít: 'is'.", grammarTopicSlug: "subject-verb-agreement" },
  { prompt: "If the survey results had been more favorable, the launch ----- earlier.", options: ["would happen", "would have happened", "happens", "will happen"], correctIndex: 1, explanationVi: "Câu điều kiện loại 3: mệnh đề chính dùng 'would have + V3'.", grammarTopicSlug: "conditionals" },
  { prompt: "The technician recommended replacing the ----- parts immediately.", options: ["defect", "defective", "defectively", "defects"], correctIndex: 1, explanationVi: "Trước danh từ 'parts' cần tính từ: 'defective' (bị lỗi).", grammarTopicSlug: "adjectives", vocabularyFocus: ["defective"] },
];
